### ISSUE TITLE
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'PurchaseResult'

### ISSUE THREAD

**Issue by meszarosdezso** [dooboolab/flutter_inapp_purchase#100]
### Actual behavior 

type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'PurchaseResult'
E/flutter (12090): #0 FlutterInappPurchase.consumePurchaseAndroid  package:flutter_inapp_purchase/flutter_inapp_purchase.dart:385

### Steps to reproduce the behavior

**Comment by hyochan** [comment]
Sorry for this. I've release 2.0.0+8. I've not made correct tying interface as in #99. I've fixed these.
