### ISSUE TITLE
Handle Refund event

### ISSUE THREAD

**Issue by mliitfall** [dooboolab/flutter_inapp_purchase#103]
Hi, thanks for this package!
Just want to know how to handle when user make a refund.
```dart
 StreamSubscription _purchaseUpdatedSubscription = FlutterInappPurchase.purchaseUpdated.listen((productItem) {
    removeAds = true;
   Pref.saveData();
  });
```
When users have succesfully buy the product, It save in preferences local data. But when they refund, all money is back and they got removeAds to true already! I want also make removeAds to false when they refunded. Can anyone explain please?

**Comment by hyochan** [comment]
Try this solution in `react-native-iap`.
![image](https://user-images.githubusercontent.com/27461460/65970294-34e80800-e4a1-11e9-8115-26b03a21e06f.png)

**Comment by dipinarora9** [comment]
Hi @mliitfall ,
for checking that if a user has refunded an in app purchase, you could set a function to be called upon app startup once in a day, that verifies that of the purchase for you. Moreover, if your app connects with your own server while using the app, you could set up real time developer notifications in your server via the play apis which will report your server when a user refunds a purchase or cancels a subscription.

if you have a consumable product, you could verify details like consumption details, purchase state after querying previous purchases from the following statement.
```
List<PurchasedItem> items =
          await FlutterInappPurchase.instance.getAvailablePurchases();
```

more reference here - https://developer.android.com/google/play/billing/realtime_developer_notifications

https://developers.google.com/android-publisher/api-ref/purchases/products

https://developers.google.com/android-publisher/api-ref/purchases/subscriptions
