### ISSUE TITLE
Is there a way of being notified when a product is already purchased?

### ISSUE THREAD

**Issue by Donerkebap13** [dooboolab/flutter_inapp_purchase#113]
Greetings!

First of all, thanks for the hard work!

I'm not able to find a way of being notified when a non-consumable product's been purchased before.

For example, if after a re-install I try to buy an already owned product, the message of "You already own this. We'll restore it for free" is shown, but I'm not notified in any way, so I can't restore anything client side.

Is there a way of being notified about this? I'm using version 2.0.2 and I'm testing IOS right now

Thank you in advance!

**Comment by Redeyes-Game** [comment]
@Donerkebap13 I think you need to use getAvailablePurchases() method to get purchases previously made

**Comment by xPutnikx** [comment]
@Donerkebap13 I think you need to use `getAvailablePurchases` method to get previously made purchases

**Comment by jesuslou** [comment]
I see. So, when do you recommend to call and process this? During startup of just before trying to purchase? I'd put it on launch but I don't know if I'm missing something. It's my first time dealing with non-consumable in app purchases.

Thanks in advance!

**Comment by xPutnikx** [comment]
@jesuslou I would use it during startup if you want to properly display the app state.

**Comment by boylenssen** [comment]
@xPutnikx when I call it on startup on iOS, I get a popup that the user must sign in on iTunes (while it already is signed in). can I prevent this? Can I check if a user purchased something without logging in?

**Comment by Donerkebap13** [comment]
@boylenssen afaik that only happens in sandbox mode with sandbox accounts. I've released an app calling `getAvailablePurchases` on startup and no itunes popup is shown
