### ISSUE TITLE
Plugin throws exceptions with flutter v1.10.7 beta

### ISSUE THREAD

**Issue by Jon-Salmon** [dooboolab/flutter_inapp_purchase#116]
On the latest beta version of flutter, dart errors are thrown when a purchase is requested.

I believe this may be due to this dart change with how `Future<Null>` is interpreted:
https://github.com/dart-lang/sdk/issues/37985

```
E/flutter (13113): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'String' is not a subtype of type 'Null'
E/flutter (13113): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:13)
E/flutter (13113): <asynchronous suspension>
E/flutter (13113): #1      FlutterInappPurchase.requestPurchase (package:flutter_inapp_purchase/flutter_inapp_purchase.dart:229:29)
E/flutter (13113): <asynchronous suspension>
```

**Comment by hyochan** [comment]
Do you think you can help out giving any other `PR`?

**Comment by Jon-Salmon** [comment]
What was the motivation for some of the methods to return `Future<Null>` instead of `Future`? I believe this is the only change that is required.

**Comment by Jon-Salmon** [comment]
I have created pull request #117 which I believe fixes this issue.

Please test it however as I have only performed basic tests.
