### ISSUE TITLE
"requestSubscription" never completes future on Android

### ISSUE THREAD

**Issue by nucleartux** [dooboolab/flutter_inapp_purchase#119]
### Version of flutter_inapp_purchase
2.0.4
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
`requestSubscription` should complete (`result.success` missing in Android code but I'm not expert here) in any case.
### Actual behavior
`requestSubscription` never returns result. So this code will wait infinitely to complete:
```
await FlutterInappPurchase.instance.requestSubscription(productId);
```
Without `await` everything is fine of course. But I spent one hour to realize where is mistake.
### Tested environment (Emulator? Real Device?)
Emulator

**Comment by hyochan** [comment]
Can you can test `iap` in android with emulator?

Also, `promise` return is deprecated from `2.0.0` and those are handled with `purchaseUpdateListener` and `purchaseErrorListener`.

**Comment by nucleartux** [comment]
Yes, but it's still `future`, so it should not be future at all or should return any result.
Because:
```
await FlutterInappPurchase.instance.requestSubscription(productId);
print('something');
```
Second row will never be executed.

**Comment by pratikpparikh** [comment]
@hyochan i am running into this same problem, moreover it does not call purchase update and return "Couldn't find purchase lists, trying to find single data."

**Comment by pratikpparikh** [comment]
I finally realized what @nucleartux  was trying to convey.  Thank you, @nucleartux 

It be nice to fix this.

**Comment by MilesAdamson** [comment]
just ran into this issue
