### ISSUE TITLE
Keep getting 'sign in with Apple ID' when I want to check purchases

### ISSUE THREAD

**Issue by boylenssen** [dooboolab/flutter_inapp_purchase#120]
### Version of flutter_inapp_purchase
2.0.3

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
User is logged in on the device. It should return the items the user has purchased. I'm using 'auto renewable subscription'.

### Actual behavior
It shows a popup that the user must log in with Apple ID.

### Tested environment (Emulator? Real Device?)
Both, also testers via Testflight

### Steps to reproduce the behavior
do ```await _purchaseInstance.getAvailablePurchases();```

**Comment by hyochan** [comment]
If I am correct, user should login to apple id if they want to fetch their apis. If you want to check purchases without it, you should check the `receipt` which you should save somewhere else when user finish the `payment`.

**Comment by boylenssen** [comment]
I'm an Android guy, so this is new to me. On Android, I can use check the purchase status and all is fine.

But what if you get a new phone, you install my app on it, how do I check if you have subscribed to specific things? My app doesn't show ads to these people, so I want to check when starting the app if they have a subscription.

If they are bother with a pop-up, they won't understand why that is.
