### ISSUE TITLE
Random Error With Subscriptions

### ISSUE THREAD

**Issue by Nicola-Cestaro** [dooboolab/flutter_inapp_purchase#123]
### Version of flutter_inapp_purchase
2.0.4
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Subscribe the user
### Actual behavior
W/BillingClient(23279): Exception while launching billing flow: ; for sku: com.onemoreday.six_months_premium; try to reconnect
E/DoobooUtils(23279): Error Code : -1
### Tested environment (Emulator? Real Device?)
Real Device both on release and on debug

Everything worked fine for a month than all of a sudden it stopped working, I get this Error -1 when I try to request the purchase of a subscription.

**Comment by hyochan** [comment]
I think we need minimal reproduction to further investigate this 😥

**Comment by mariogorki94** [comment]
I am having the same problem with this plugin. I am connected i am able do get all available products, only when requesting purchase or subscription i get.
W/BillingClient( 6327): Exception while launching billing flow: ; for sku: subscription_lifetime_promo; try to reconnect
E/DoobooUtils( 6327): Error Code : -1

**Comment by solokingjec** [comment]
I am also having this issue
