### ISSUE TITLE
How to check purchase expires date

### ISSUE THREAD

**Issue by LSFMint** [dooboolab/flutter_inapp_purchase#124]
Platform: iOS

After getting the purchased history from getAvailablePurchases(). Does the return data can determine the expired date from auto subscription? How to know the subscription's active period?

**Comment by hyochan** [comment]
There is [related post](https://github.com/dooboolab/react-native-iap/issues/275#issuecomment-425185861) in [react-native-iap repo](https://github.com/dooboolab/react-native-iap). The idea is, you should check the `receipt`.
