### ISSUE TITLE
Purchase is working on ios but sometimes will throw an error

### ISSUE THREAD

**Issue by christianr11** [dooboolab/flutter_inapp_purchase#128]
### Version of flutter_inapp_purchase
2.0.4
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
When i click subscribe the purchaseUpdated.listen should work (will update backend)
### Actual behavior
If you try it for the first time it works well but if you tried it multiple times already it will throw an error 'Purchased Failed! An unknown or unexpected error has occurred. Please try again later'. But the device will show a message that the transaction was successful, if you click the subscribe button it says that you are already subscribed.
### Tested environment (Emulator? Real Device?)
Real Device

--
Purchase Failed  !!
2019-11-26 18:15:51.460264+0800 Runner[701:144571] flutter: purchase-error: responseCode: null, debugMessage: SKPaymentTransactionStateFailed, code: E_UNKNOWN, message: An unknown or unexpected error has occured. Please try again later. (Error code: -1001)

![Uploading Screen Shot 2019-11-26 at 4.12.13 PM.png…]()

**Comment by hyochan** [comment]
I hope you can come back with a better example so someone can reach out to your problem in detail.

Also, you've been uploading a screetshot 😁.
