### ISSUE TITLE
Flutter - Not able to update or delete the managed products inside in app purchases?

### ISSUE THREAD

**Issue by JayM96** [dooboolab/flutter_inapp_purchase#129]
Hello,

Currently, I am implementing in app purchase in flutter using the FlutterInAppPurchase Plugin.

I have 3 Items in my managed products in my google play console like,

['get_10_coins', 'get_100_coins', 'get_1000_coins']
Now, I am updated the details of the "get_10_coins" product. But, still It's not getting reflected in the app when i use FlutterInappPurchase.instance.getProducts(_productLists); method.

Then i deleted that product and added a new managed product like "get_50_coins". But, still it is showing me the old details of the "get_10_coins" product.

// fetching products using the following code
List<IAPItem> items = await FlutterInappPurchase.instance.getProducts(_productLists);
Can anyone tell me what can be the problem ? I have already uninstalled app as well.

Thanks.

**Comment by hyochan** [comment]
iap server in `android` will take max 48hours before it actually updates your client-side. Therefore, if you want this to be updated as soon as possible, I'd recommend you to create new product `get_50_coins` and then just query ['get_50_coins', 'get_100_coins', 'get_1000_coins'] by removing 'get_10_coins'.
