### ISSUE TITLE
getPendingTransactionsIOS returns purchases even though they are finished

### ISSUE THREAD

**Issue by dennis-tra** [dooboolab/flutter_inapp_purchase#131]
### Version of flutter_inapp_purchase
^2.0.5

### Platforms you faced the error (IOS or Android or both?)
IOS

### Steps to reproduce:
* Right after app start I'm starting to listen to the `purchaseUpdate` and `purchaseError` streams.
* Request available products
* Purchase a product
* Send receipt to my backend
* Verify the receipt and send `success` response
* Finish transaction on client by calling `finishTransaction`

### Actual behavior
Now When I'm calling `getPendingTransactionsIOS` I will still receive the purchase I just made. Is that intended? Does it take some time to also update the data source that `getPendingTransactionsIOS` is using?

### Expected behavior
`getPendingTransactionsIOS` returns an empty list.

### Tested environment (Emulator? Real Device?)
Real device in with a sandbox user

Furthermore if I had not called `finishTransaction` I would have expected to see the purchase coming in through the `purchaseUpdate` stream again right after I have subscribed to it (e.g. after an app restart). This was not the case - I will only see the pending transaction when I call `getPendingTransactionsIOS` which returns even "non-pending" purchases. Do I also understand something wrong here?

**Comment by godzeit** [comment]
Face same issue. Please help to solve ASAP
