### ISSUE TITLE
getPurchaseHistory - throws PlatformException(getPurchaseHistoryByType, E_NETWORK_ERROR, The service is disconnected (check your internet connection.))

### ISSUE THREAD

**Issue by dvorajo6** [dooboolab/flutter_inapp_purchase#132]
### Version of flutter_inapp_purchase
2.0.5 and 2.0.4

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Servise return list of purchases.
It happens only in release. In debug mode we recieve expected list of purchases. 

### Actual behavior
throws PlatformException(getPurchaseHistoryByType, E_NETWORK_ERROR, The service is disconnected (check your internet connection.))

### Tested environment (Emulator? Real Device?)
Real devices

**Comment by hyochan** [comment]
Hm.. I also don't know what's wrong with production and debug mode in your case. Please feel free to come back if you find additional information.

**Comment by dvorajo6** [comment]
Approximately  from 2019-11-21 we are on version ^2.0.4.
Exception start occuring from 2019-12-02 .

We call getPurchaseHistory in main.dart after app start.

void main() async{
  CatcherOptions debugOptions =
      CatcherOptions(  DialogReportMode(), 
      [RsgHttpExceptionHandler(), ConsoleHandler()]);
  CatcherOptions releaseOptions = 
    CatcherOptions(SilentReportMode(), 
    [RsgHttpExceptionHandler()
  ]);

  Catcher(MyApp(), debugConfig: debugOptions, releaseConfig: releaseOptions);

  try {
    await FlutterInappPurchase.instance.initConnection;
    List<PurchasedItem> subscriptions = await FlutterInappPurchase.instance.getPurchaseHistory();

**Comment by dvorajo6** [comment]
here is stackTrace.

#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316)
<asynchronous suspension>
#2      FlutterInappPurchase.getPurchaseHistory (package:flutter_inapp_purchase/flutter_inapp_purchase.dart:161)
<asynchronous suspension>
#3      main (package:restartgym/main.dart:42)
<asynchronous suspension>
#4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:216)
#5      _rootRun (dart:async/zone.dart:1124)
#6      _CustomZone.run (dart:async/zone.dart:1021)
#7      _runZoned (dart:async/zone.dart:1516)
#8      runZoned (dart:async/zone.dart:1500)
#9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:208)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172)

**Comment by egorges** [comment]
I am currently having the same error in iOS simulator, although Android emulator works.

**Comment by egorges** [comment]
As stated in https://medium.com/ios-development-tips-and-tricks/working-with-ios-in-app-purchases-e4b55491479b

> "You must test the in-app purchases on a real device. Purchases will always fail on iOS simulator."

Is that still true?

**Comment by JulianBissekkou** [comment]
If you are on android, check the settings and make sure that a google account is logged in. This was the issue in my case.
