### ISSUE TITLE
Support IAP in kindle devices

### ISSUE THREAD

**Issue by Rockvole** [dooboolab/flutter_inapp_purchase#14]
Hi,
Do you plan to add support for Amazon Kindle devices ?

You can see more details here :
https://github.com/JackAppDev/flutter_iap/issues/11

I asked Amazon also :
https://forums.developer.amazon.com/questions/180254/support-flutter-iap-for-kindle-devices.html

**Comment by dooboolab** [comment]
@Rockvole I've gone trough [wiki](https://en.wikipedia.org/wiki/Fire_OS).

<img width="1413" alt="screen shot 2018-08-15 at 1 50 30 am" src="https://user-images.githubusercontent.com/27461460/44105743-9e21243c-a02d-11e8-89d1-57c055c46680.png">

Following the screenshot I've posted, this is quite a burden for this module.[Here](https://developer.amazon.com/docs/in-app-purchasing/iap-get-started.html) explains that we need extra sdk to able to use the IAP. Not all the people using this module will need this to support kindle device.

Kindle is not ready for flutter I think.

**Comment by Rockvole** [comment]
Hi,
I added support for Amazon Kindle In-App purchases
https://github.com/dooboolab/flutter_inapp_purchase/pull/36

**Comment by Rockvole** [comment]
Amazon has a very neat testing facility. You install the Amazon App Tester (AAT) :
https://www.amazon.com/Amazon-App-Tester/dp/B00BN3YZM2
You put this file into /sdcard on the phone :
https://github.com/Rockvole/flutter_inapp_purchase/blob/amazon/ancillary/amazon.sdktester.json

Then you can test purchases and the AAT intercepts the communications. You can examine and clear purchases in the AAT. The AAT sends notifications if the API is not used correctly.

Do any of the other committers have Kindles to help with testing ?
@lukepighetti @emostar @alamboley

**Comment by lukepighetti** [comment]
@Rockvole I do not, I haven't taken the platform seriously. What device do you recommend for testing? Is there an emulator available?

**Comment by Rockvole** [comment]
Hi Luke,
Unfortunately, they no longer have an emulator available. 
The Amazon market is admittedly smaller, but Amazon have 10% of the tablet market share. Also, most people have IAP enabled because it is tied to their Amazon account.
The app which I am porting is :
[AAC Keyboard with friends](https://play.google.com/store/apps/details?id=com.rockvole.kbmlviewer)
It is for people with speech disabilities. I want to add it to the Kindle because the speech is very nice and the Kindle Fires are low cost. These types of apps are often used by children who may regularly damage the devices. I have a Kindle Fire HD 6 ($25 on ebay.com).

**Comment by Rockvole** [comment]
So I got my app approved on the amazon store. It was fairly smooth. I discovered a bug in flutter with obfuscation which caused me delays working out what that was all about.
I like that on the kindle people can search for your app from the search bar at the top of the front page.

Also I like that you can target a currency which is not your own and set a price in that you will target (like obviously USD). On the play store I have to try to guess an approximation in my own currency that makes USD what I want, so its not right.
https://www.amazon.com/gp/product/B07HNLM31K

If you take my pull request I will put some notes in an amazon readme so that its smoother for people while I still remember the gotchas.

**Comment by Rockvole** [comment]
I think this issue is complete now.

**Comment by Rockvole** [comment]
For those who are here wondering if it might be worthwhile porting their flutter app to Amazon.
I can tell you that for me its been worth it.
My app AAC Keyboard (linked above) from the total number of downloads on Google play I have 43% of that figure also downloaded on Amazon.
So I guess it depends on what type of App you are installing and whether there is much competition for your type of app on the Amazon store.
My other app (food related) which has been on Amazon for a few years only has more like 5% of the total of the google play downloads which I think is more typical.

**Comment by Rockvole** [comment]
The Amazon store may become more important soon since it will be used for Android apps in Windows 11.
https://www.theverge.com/2021/6/24/22548428/microsoft-windows-11-android-apps-support-amazon-store
