### ISSUE TITLE
Error In Usage Guide: FlutterInappPurchase.initConnection

### ISSUE THREAD

**Issue by esDotDev** [dooboolab/flutter_inapp_purchase#142]
`await FlutterInappPurchase.initConnection;` should be `await FlutterInappPurchase.instance.initConnection;`

Also, this is against dart language conventions to use an accessor this way. If a function does something, like init() does, it should generally be a proper function().

**Comment by hyochan** [comment]
@esDotDev Could you share your idea or give us a `PR` on how would you like this to be?

**Comment by esDotDev** [comment]
It's just that getters are generally expected to just return something, not do something. 
So I'm just suggesting using:
FlutterInappPurchase.instance.initConnection**_()_**;

And doing the same for all the instances. I do realize this means breaking the API surface right now, which is probably not an option :(  So not really sure why I brought it up now that I think about it!

**Comment by sawproduction** [comment]
The issue arrives it is depreciated in flutter 3.0
