### ISSUE TITLE
Why my orders was refunded in Order Management in Play Console?

### ISSUE THREAD

**Issue by Medrov** [dooboolab/flutter_inapp_purchase#143]
I use this plugin to make quality transactions, without problem. But I have a problem, when my users make a purchase, I get a new paid order in order management. But three days later, Google asks for refund this order and money, he explain this by this. 

> "please note that if you are already consuming purchases via consumeAsync(), you do not need to make any further changes if you consume purchases within 3 days(72hrs), as consumeAsync() automatically acknowledges a purchase. Failure to properly acknowledge purchases will result in purchases being refunded."

I use non-consumable purchases for this. Honestly, I do understand why this happen, but I can't understand what's whrong with my code. Please, help me, to handle with my code)

> I use this code for execute purchase

  ```
Map<int, IAPItem> _items = {};
  StreamSubscription _purchaseUpdatedSubscription;

  @override
  void initState() {
    asyncInitState();
    super.initState();
  }

  asyncInitState() async {
    await FlutterInappPurchase.instance.initConnection;
    _purchaseUpdatedSubscription = FlutterInappPurchase.purchaseUpdated.listen((productItem) {
      print('purchase-updated: $productItem');
      _handlePurchaseUpdate(productItem);
    });
    await _getItems();
    await _getPurchases();
  }

  Future<void> _getItems() async {
    List<IAPItem> items = await FlutterInappPurchase.instance.getProducts([
      beginnerString,
      widget.dataHandler.license[beginnerString] ?? false
          ? '${advancedString}_discount'
          : advancedString,
    ]);
    for (IAPItem item in items) {
      if (item.productId == '${beginnerString}_full') {
      } else {
        setState(() {
          _items[item.productId == beginnerString ? 0 : 1] = (item);
        });
      }
    }
  }

  _getPurchases() async {
    List<PurchasedItem> purchases = await FlutterInappPurchase.instance.getAvailablePurchases();
    for (PurchasedItem item in purchases) {
      _verifyPurchase(item);
    }
  }

  _purchase(IAPItem item) {
    print('tried purchasing: ${item.productId}');
    FlutterInappPurchase.instance.requestPurchase(item.productId);
  }

  _handlePurchaseUpdate(PurchasedItem productItem) async {
    print('purchased: ${productItem.productId}');
    if (await _verifyPurchase(productItem)) {
      deliverProduct(productItem);
    }
  }

  Future<bool> _verifyPurchase(PurchasedItem productItem) async {
    if (productItem.purchaseStateAndroid == 1) {
      if (!productItem.isAcknowledgedAndroid) {
        await FlutterInappPurchase.instance.acknowledgePurchaseAndroid(productItem.purchaseToken,
            developerPayload: productItem.developerPayloadAndroid);
      }
      return true;
    }
    return false;
  }

  deliverProduct(PurchasedItem productItem) async {
    setState(() {
      widget.dataHandler.license[
              '${productItem.productId.contains(advancedString) ? advancedString : beginnerString}'] =
          true;
    });
    Navigator.of(context)
        .pushReplacement(MaterialPageRoute(builder: (context) => MainHandler(widget.dataHandler)));
  }
 @override
  Future dispose() async {
    super.dispose();
    await FlutterInappPurchase.instance.endConnection;
    _purchaseUpdatedSubscription.cancel();
    _purchaseUpdatedSubscription = null;
  }
```

> How can I solve this problem?

**Comment by Gyoko** [comment]
I have the same problem. All of my subscription orders are getting refunded, and users are confirming that this is happening without their consent. 

I'm using this to do the purchase
` FlutterInappPurchase.instance
                                  .requestPurchase('$id');`

**Comment by Gyoko** [comment]
GooglePlay staff is investigating the issue to verify if somehow it's not on their side. Currently I'm replacing this library with the official `in_app_purchase`.

From now on I will avoid this plugin like fire. I don't care if author made this refund bug deliberately or by mistake.

**Comment by Gyoko** [comment]
Nope. Looks like I skipped the "verify purchase" step. Sorry, author. But you should highlight the importance of the step. Highlight it in bold red or something.

**Comment by hyochan** [comment]
@Gyoko You've done it right. Please give any other helpful `PR` for those who might suffer from same problem. Since this is an open source, you can always help others by `PRing`. Not only the author should take care of all the docs and guideline.

**Comment by uzumaki258** [comment]
Hello @Medrov , did you solve this problem ?
I faced same issue, all subscription has been refunded. ( about 400$ )
So sad.

I have added verify_purchase and call acknowledgePurchaseAndroid, but user still get refund like you, but still no luck

**Comment by uzumaki258** [comment]
Sorry, I forgot verify purchase. It works now. 
Thanks

**Comment by phamtuongvan** [comment]
How to verify purchase??

**Comment by ffkaan** [comment]
Hello, I have the same problem, how did you solve it?
