### ISSUE TITLE
How to verify '非续期订阅' or '自动续期订阅',

### ISSUE THREAD

**Issue by HJT916109796** [dooboolab/flutter_inapp_purchase#148]
### Version of flutter_inapp_purchase

```dart
flutter_inapp_purchase: ^2.1.0
```

### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
provie me a method so i can verify a receipt for this situation , and i need to buy some product many times,not only once .
### Actual behavior
When i buy this product twice , it shows me that i already bought this product .
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior
First you call method  request purchase after you finish this behavior , you observe the status of the product , then you call 'FlutterInappPurchase.instance
            .finishTransactionIOS(productItem.purchaseToken)' , result.debugMessage == 'finishTransaction', next call this twice.

**Comment by AnNEDoMini** [comment]
Simple:
```
    purchaseUpdatedSubscription = FlutterInappPurchase.purchaseUpdated.listen((donateItem) async {
      print('donated - ${donateItem.toString()}');

      switch(donateItem.productId) {
        case SKUS.DONATE_1:
        case SKUS.DONATE_2:
        case SKUS.DONATE_3:
          Map<String, String> receiptBody = {
            'receipt-data': purchasedItem.transactionReceipt,
            'password': WConstants.BILLING_SHARED_SECRET_IOS
          };
          await FlutterInappPurchase.instance.validateReceiptIos(receiptBody: receiptBody, isTest: false);
          await FlutterInappPurchase.instance.finishTransaction(donateItem, isConsumable: true);
          purchaseUpdatedSubscription.cancel();
          break;
      }
    });
```
This code is from live app both for android and ios (changed it a bit to make more clear)

**Comment by HJT916109796** [comment]
same result

**Comment by ipolx** [comment]
> Simple:
> 
> ```
>     purchaseUpdatedSubscription = FlutterInappPurchase.purchaseUpdated.listen((donateItem) async {
>       print('donated - ${donateItem.toString()}');
> 
>       switch(donateItem.productId) {
>         case SKUS.DONATE_1:
>         case SKUS.DONATE_2:
>         case SKUS.DONATE_3:
>           Map<String, String> receiptBody = {
>             'receipt-data': purchasedItem.transactionReceipt,
>             'password': WConstants.BILLING_SHARED_SECRET_IOS
>           };
>           await FlutterInappPurchase.instance.validateReceiptIos(receiptBody: receiptBody, isTest: false);
>           await FlutterInappPurchase.instance.finishTransaction(donateItem, isConsumable: true);
>           purchaseUpdatedSubscription.cancel();
>           break;
>       }
>     });
> ```
> 
> This code is from live app both for android and ios (changed it a bit to make more clear)

One mention for this: if you have reward function on cases, "purchaseUpdatedSubscription.cancel();" will not allow the function to run every time, just for the first time !
Example: If you want to increase coins/gems/diamons etc. using this method.
