### ISSUE TITLE
How to access existing (purchased) subscriptions in iOS?

### ISSUE THREAD

**Issue by casualcoder404** [dooboolab/flutter_inapp_purchase#149]
### Version of flutter_inapp_purchase   
flutter_inapp_purchase: ^2.1.0

### Platforms you faced the error (IOS or Android or both?)
 iOS

### Expected behavior  : 
return only the purchased products .

### Actual behavior: 
returns purchase product history.

**Comment by hyochan** [comment]
As far as I know, you can do this by validating receipts in `ios`.
