### ISSUE TITLE
FlutterInappPurchase.getProducts(skus) returns an empty list

### ISSUE THREAD

**Issue by GervaisYO** [dooboolab/flutter_inapp_purchase#15]
I'm currently using the library to fetch products from google play console.
For this i used the method:

`FlutterInappPurchase.getProducts(skus)`

But i'm getting an empty list back, although i created in my google play console account the IAP product.
Is there something else i need to configure in order to make this works?

### Version of flutter_inapp_purchase
version 0.4.3

### Platforms you faced the error (IOS or Android or both?)
Sony XPeria Z5 Premium

### Expected behavior
List of product should not be empty

### Actual behavior
List of product is empty

### Tested environment (Emulator? Real Device?)
Real device

**Comment by GervaisYO** [comment]
Having a look i was wondering how this should actually work. With native IOS the IAP Products are grouped by bundle Id and i only get IAP Products for a specific bundle Id (an app) and the id of the IAP Product.

But when using this library i didn't specify an application id. Should i specify one? If yes, where should i do it?

Thank you

**Comment by dooboolab** [comment]
@GervaisYO You needed to specify the id in past version of iap module in android. I am currently using the recent version so you don't need to specify extra application id for this. Also for getting empty product list, you may wait for few hours to actually getting the purchase items. You may follow [here](https://github.com/dooboolab/react-native-iap/issues/77).
