### ISSUE TITLE
iOS: purchases not starting

### ISSUE THREAD

**Issue by AnNEDoMini** [dooboolab/flutter_inapp_purchase#150]
### Version of flutter_inapp_purchase
2.1.0
### Platforms you faced the error (IOS or Android or both?)
iOS (android works perfect)
### Expected behavior
User starts purchase flow
### Actual behavior
```
FlutterInappPurchase.instance.requestPurchase(item.productId);
```
Dont do anything
### Tested environment (Emulator? Real Device?)
Real device only with app from appstore.

### Steps to reproduce the behavior
https://apps.apple.com/us/app/knowledge-base-for-wot/id1480841499?ls=1
Main screen -> settings -> donations/premium -> click any purchase -> nothing happens

Strange behavior: android works perfectly, iOS with sandbox users also works (user can start purchase flow both for onetime purchases and autorenewable subscriptions), but for app in appstore - nothing happens when user clicks donate or purchasse? app doesnt react in any way.

**Comment by janosdupai** [comment]
I have the same issue. Is there any solution?
