### ISSUE TITLE
test ios get products on emulator mac

### ISSUE THREAD

**Issue by ymanta** [dooboolab/flutter_inapp_purchase#157]
### Version of flutter_inapp_purchase
2.1.0

### Platforms you faced the error (IOS or Android or both?)
ios

### Expected behavior
show suscriptions created on app store

### Actual behavior
dont show on emulator

### Tested environment (Emulator? Real Device?)
Emulator

### Steps to reproduce the behavior
This is he code that i use:
import 'package:flutter/cupertino.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'dart:async';
import 'dart:io';

import 'package:flutter/services.dart';
import 'package:flutter_inapp_purchase/flutter_inapp_purchase.dart';
import 'package:url_launcher/url_launcher.dart';

import 'estilos.dart';

class planes extends StatefulWidget {
  @override
  _planesState createState() => new _planesState();
}

class _planesState extends State<planes> {
  StreamSubscription _purchaseUpdatedSubscription;
  StreamSubscription _purchaseErrorSubscription;
  StreamSubscription _conectionSubscription;
  final List<String> _productLists = Platform.isAndroid
      ? [
    'android.test.purchased',
    'point_1000',
    '5000_point',
    'android.test.canceled',
  ]
      : ['com.cooni.point1000', 'com.cooni.point5000'];

  String _platformVersion = 'Unknown';
  List<IAPItem> _items = [];
  List<PurchasedItem> _purchases = [];

  @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  @override
  void dispose() {
    if (_conectionSubscription != null) {
      _conectionSubscription.cancel();
      _conectionSubscription = null;
    }
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initPlatformState() async {
    String platformVersion;

    // Platform messages may fail, so we use a try/catch PlatformException.
    try {
      platformVersion = await FlutterInappPurchase.instance.platformVersion;
    } on PlatformException {
      platformVersion = 'Failed to get platform version.';
    }

    // prepare
    var result = await FlutterInappPurchase.instance.initConnection;
    print('resultado de la conexión: $result');
    print('plataforma ios o android: $platformVersion');
    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    setState(() {
      _platformVersion = platformVersion;
    });

    // refresh items for android
    try {
      String msg = await FlutterInappPurchase.instance.consumeAllItems;
      print('consumeAllItems: $msg');
    } catch (err) {
      print('consumeAllItems error: $err');
    }

    _conectionSubscription = FlutterInappPurchase.connectionUpdated.listen((connected) {
      print('connected: $connected');
    });

    _purchaseUpdatedSubscription = FlutterInappPurchase.purchaseUpdated.listen((productItem) {
      print('purchase-updated: $productItem');
    });

    _purchaseErrorSubscription = FlutterInappPurchase.purchaseError.listen((purchaseError) {
      print('purchase-error: $purchaseError');
    });
  }

  void _requestPurchase(IAPItem item) {
    FlutterInappPurchase.instance.requestPurchase(item.productId);
  }

  Future _getProduct() async {
    List<IAPItem> items = await FlutterInappPurchase.instance.getProducts(_productLists);
    for (var item in items) {
      print('${item.toString()}');
      this._items.add(item);
    }

    setState(() {
      this._items = items;
      this._purchases = [];
    });
  }

  Future _getPurchases() async {
    List<PurchasedItem> items =
    await FlutterInappPurchase.instance.getAvailablePurchases();
    for (var item in items) {
      print('${item.toString()}');
      this._purchases.add(item);
    }

    setState(() {
      this._items = [];
      this._purchases = items;
    });
  }

  Future _getPurchaseHistory() async {
    List<PurchasedItem> items = await FlutterInappPurchase.instance.getPurchaseHistory();
    for (var item in items) {
      print('${item.toString()}');
      this._purchases.add(item);
    }

    setState(() {
      this._items = [];
      this._purchases = items;
    });
  }

  List<Widget> _renderInApps() {
    List<Widget> widgets = this
        ._items
        .map((item) => Container(
          child: Container(
            child: Column(
              children: <Widget>[
                Container(
                  child: Column(
                    children: <Widget>[
                      Text(item.title,style: TextStyle(color: Colors.white,fontWeight:FontWeight.bold,fontSize: 16.0),),
                      SizedBox(height: 10.0,),
                      Text(item.description,style: TextStyle(color: Colors.white),textAlign: TextAlign.center,),
                      SizedBox(height: 10.0,),
                    ],
                  ),
                ),

                FlatButton(
                  //color: Colors.orange,
                  onPressed: () {
                    print("---------- Se compro suscripción yeee");
                    this._requestPurchase(item);
                  },
                  child: Container(
                    padding: EdgeInsets.only(top: 10.0,bottom: 10.0,left: 15.0,right: 15.0),
                    child: Text("Comprar",style: TextStyle(color: Colors.white),),
                    color: Color(0xff3a426f),
                  ),
            ),

                SizedBox(height: 15.0,),

                Divider(),

                SizedBox(height: 15.0,),
              ],
            ),
          ),
        ))
        .toList();
    return widgets;
  }

  List<Widget> _renderPurchases() {
      List<Widget> widgets = this
        ._purchases
        .map((item) => Container(
          margin: EdgeInsets.symmetric(vertical: 10.0),
          child: Container(
            child: Column(
              children: <Widget>[
                Container(
                  margin: EdgeInsets.only(bottom: 5.0),
                  child: Text(item.toString()),
                )
              ],
            ),
          ),
        ))
        .toList();
      return widgets;
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: new BoxDecoration(
        gradient: new LinearGradient(colors: [gradientStart, gradientEnd],
            begin: Alignment.topLeft,
            end: Alignment.bottomRight,
            stops: [0.0,1.0],
            tileMode: TileMode.clamp
        ),
      ),
      child: Scaffold(
        backgroundColor: Colors.transparent,

        appBar: new AppBar(
          title: Text('Planes'),
          centerTitle: true,
        ),

        body: Container(
          margin: EdgeInsets.all(30.0),
          decoration: BoxDecoration(
              border: Border.all(color: Colors.white)
          ),
          child: ListView(
            children: <Widget>[
              Container(
                padding: EdgeInsets.all(20.0),
                child: Column(
                  children: <Widget>[

                    RichText(
                        textAlign: TextAlign.center,
                        text: new TextSpan(
                            children: <TextSpan>[
                              new TextSpan(
                                  text:'Si necesitas más espacio para agregar contactos, C@rdin te ofrece planes a las medidas de tus necesidades',
                                  style: new TextStyle(color:Colors.white,fontSize: 16.0)
                              ),
                              new TextSpan(
                                  text:' Para más información haz clic aquí',
                                  style:new TextStyle(fontWeight: FontWeight.bold,color:Color(0xff61e9f1),fontSize: 16.0),
                                  recognizer: new TapGestureRecognizer()
                                    ..onTap =(){launch("http://cardinteligente.com/terminos-y-condiciones");}

                              ),
                            ]
                        )
                    ),
                    SizedBox(height: 30.0,),

                    Column(
                      children: <Widget>[
                        Row(
                          children: <Widget>[
                            Container(
                              child: FlatButton(
                                onPressed: () async {
                                  print("---------- Connect Billing Button Pressed");
                                  await FlutterInappPurchase.instance.initConnection;
                                },
                                child: Text('Conectar'),
                              ),
                            ),

                            Container(
                              child: FlatButton(
                                onPressed: () async {
                                  print("---------- End Connection Button Pressed");
                                  await FlutterInappPurchase.instance.endConnection;
                                  if (_purchaseUpdatedSubscription != null) {
                                    _purchaseUpdatedSubscription.cancel();
                                    _purchaseUpdatedSubscription = null;
                                  }
                                  if (_purchaseErrorSubscription != null) {
                                    _purchaseErrorSubscription.cancel();
                                    _purchaseErrorSubscription = null;
                                  }
                                  setState(() {
                                    this._items = [];
                                    this._purchases = [];
                                  });
                                },
                                child: Text('Finalizar'),
                              ),
                            )
                          ],
                        ),

                        Row(
                          children: <Widget>[
                            Container(
                              child: FlatButton(
                                onPressed: () {
                                  print("---------- Get Items Button Pressed");
                                  this._getProduct();
                                },
                                child: Text('Mostrar Items'),
                              ),
                            )
                          ],
                        ),
                      ],
                    ),

                    Column(
                      children: this._renderInApps(),
                    )

                  ],
                ),
              )
            ],

          ),
        ),
      ),
    );
  }
}

//////////
I test on android and i get the android.test.purchased info, my question is, if i used a mac and emulator, is posibly get the suscriptions from app store?, i have two : plan_intermedio and plan_basico both there with the status "ready to send", (i dont knw if this status is a problem).

**Comment by hyochan** [comment]
You should be able to get the `subscriptions` as well as `non-subscripstions`. However, the purchasing won't work in simulator.

**Comment by BadReese** [comment]
I get nothing when I called getProduct function, it cause an unknown error .

**Comment by BadReese** [comment]
PlatformException (PlatformException(E_UNKNOWN, An unknown or unexpected error has occured. Please try again later., null, null))
