### ISSUE TITLE
No callback method after successful purchase

### ISSUE THREAD

**Issue by gaojuanjuan** [dooboolab/flutter_inapp_purchase#159]
_purchaseUpdatedSubscription = FlutterInappPurchase.purchaseUpdated.listen(
      (productItem) {
        Log.d('purchase-updated: $productItem');
      },
    );
    _purchaseErrorSubscription =
        FlutterInappPurchase.purchaseError.listen((purchaseError) {
      Log.d('购买出错: $purchaseError');
    });

**Comment by egorges** [comment]
@gaojuanjuan 
Could you post a full example?

I have both functions in my code and they work properly - I initiated them in asyncInitState as suggested.

**Comment by LucasTejero** [comment]
Im having the same issue,the purchase was succesful but i had no callback
