### ISSUE TITLE
Crash with using FlutterIsolate

### ISSUE THREAD

**Issue by mrxten** [dooboolab/flutter_inapp_purchase#160]
I need to use Flutter Isolate (https://pub.dev/packages/flutter_isolate). I dont call api of your package in created isolate. but after kill isolate I got exception on your package.

### Version of flutter_inapp_purchase
2.1.1

### Platforms you faced the error (IOS or Android or both?)
iOS

### Tested environment (Emulator? Real Device?)
both

### Steps to reproduce the behavior
make spawnIsolate and after kill.

App will crash and you will see in console something like this:

> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
> 	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
> 	2   CoreFoundation                      0x00007fff23c70ff8 +[NSException raise:format:arguments:] + 88
> 	3   Foundation                          0x00007fff256e9b51 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
> 	4   Flutter                             0x0000000101da3b16 -[FlutterEngine setMessageHandlerOnChannel:binaryMessageHandler:] + 271
> 	5   flutter_inapp_purchase              0x0000000103e8917b -[FlutterInappPurchasePlugin dealloc] + 171
> 	6   libobjc.A.dylib                     0x00007fff514110d6 _ZN11objc_object17sidetable_releaseEb + 174
> 	7   libsystem_blocks.dylib              0x00007fff522d09c2 _Blo<…>

**Comment by siqwin** [comment]
Same here.

I don't use flutter_isolate directly, but I use the audio_service plugin, which internally uses flutter_isolate. The flutter_inapp_purchase cause crash when audio_service is destroying. 

Any help?

**Comment by hyochan** [comment]
@siqwin Thanks for sharing. So this doesn't look it's on our plugin so I'll close it for now.
