### ISSUE TITLE
requestPurchase error: responseCode: null, debugMessage: SKPaymentTransactionStateFailed, code: E_UNKNOWN, message: An unknown or unexpected error has occured. Please try again later.

### ISSUE THREAD

**Issue by kraa** [dooboolab/flutter_inapp_purchase#161]
### Version of flutter_inapp_purchase
^2.1.1
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
I get the list of products by FlutterInappPurchase.instance.getProducts and after that i try to run 
` 
   void _requestPurchase(IAPItem item) {. FlutterInappPurchase.instance.requestPurchase(item.productId);  }
`

Device ask me to Sign-In with apple id and after i signed my purchaseError listener catch error:
**error: responseCode: null, debugMessage: SKPaymentTransactionStateFailed, code: E_UNKNOWN, message: An unknown or unexpected error has occured. Please try again later.**

So in my log i see:
`
Purchase Started !!
Purchase Failed  !!
flutter: error: responseCode: null, debugMessage: SKPaymentTransactionStateFailed, code: E_UNKNOWN, message: An unknown or unexpected error has occured. Please try again later.
`
### Tested environment (Emulator? Real Device?)
Real Device

**Comment by JideGuru** [comment]
I still get this, any solutions please?

**Comment by vivchar** [comment]
Hi, I have the same problem, any update?

**Comment by eduardothiesen** [comment]
I'm experiencing the same issue. 

`StreamSubscription _purchaseUpdatedSubscription;
  StreamSubscription _purchaseErrorSubscription;

  final List<String> _productLists = [
    'auto_renewable_monthly_subscription',
  ];

  String _platformVersion = 'Unknown';

  List<IAPItem> _items = [];
  List<PurchasedItem> _purchases = [];

  bool hasConnectivity = false;

  @override
  initState() {
    initPlatformState();

    super.initState();
  }

  Future<void> initPlatformState() async {
    try {
      print('Will teste connectivity');
      final result = await InternetAddress.lookup('google.com');
      print(result);
      hasConnectivity = true;
    } on SocketException catch (_) {
      print('no connection');
      hasConnectivity = false;
    }

    String platformVersion;
    // Platform messages may fail, so we use a try/catch PlatformException.
    try {
      platformVersion = await FlutterInappPurchase.instance.platformVersion;
    } on PlatformException {
      platformVersion = 'Failed to get platform version.';
    }

    // prepare
    var result = await FlutterInappPurchase.instance.initConnection;
    print('result: $result');

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    setState(() {
      _platformVersion = platformVersion;
    });

    // refresh items for android
    try {
      String msg = await FlutterInappPurchase.instance.consumeAllItems;
      print('consumeAllItems: $msg');
    } catch (err) {
      print('consumeAllItems error: $err');
    }

    _purchaseUpdatedSubscription =
        FlutterInappPurchase.purchaseUpdated.listen((productItem) async {
      print('will get purchases');
      await _getPurchases();
      print('did get purchases');
      for (PurchasedItem purchasedItem in _purchases) {
        if (purchasedItem.transactionStateIOS == TransactionState.purchased ||
            purchasedItem.transactionStateIOS == TransactionState.restored) {
          completePurchase(purchasedItem);
        }
      }
    });

    _purchaseErrorSubscription =
        FlutterInappPurchase.purchaseError.listen((purchaseError) {
      print('_purchaseErrorSubscription');
      print(purchaseError.toString());
      print(purchaseError);
      print(purchaseError.debugMessage);
      for (PurchasedItem purchasedItem in _purchases) {
        if (purchasedItem.transactionStateIOS == TransactionState.purchased ||
            purchasedItem.transactionStateIOS == TransactionState.restored) {
          completePurchase(purchasedItem);
        }
      }
    });

    _getProduct();
    await _getPurchaseHistory();
  }

void _requestPurchase(IAPItem item) {
    print('_requestPurchase $item');
    FlutterInappPurchase.instance.requestSubscription(item.productId);
  }

RoundedButton(
                  title: 'CONTINUAR',
                  color: kGreen,
                  onPressed: () {
                    if (Platform.isIOS) {
                      if (_purchases != null &&
                          _purchases.length > 0 &&
                          (_purchases[0].transactionStateIOS ==
                                  TransactionState.purchased ||
                              _purchases[0].transactionStateIOS ==
                                  TransactionState.restored)) {
                        print('will restore');
                        try {
                          completePurchase(_purchases[0]);
                        } catch (e) {
                          print(e);
                        }
                      } else {
                        print('will request');
                        print(_items);
                        try {
                          _requestPurchase(_items[0]);
                        } catch (e) {
                          print(e);
                        }
                      }
                    } else {
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (context) => FarmsModule(
                            widget.firebaseUser,
                            widget.user,
                          ),
                        ),
                      );
                    }
                  },
                ),
`

**Comment by BadReese** [comment]
this issue should not be closed !

**Comment by ksydex** [comment]
Same issue. Should i accep agreement on paid applications in itunesconnect before testing?

**Comment by Rajdeep-Das** [comment]
flutter: purchase-error: responseCode: null, debugMessage: SKPaymentTransactionStateFailed, code: E_UNKNOWN, message: An unknown or unexpected error has occured. Please try again later.
<img width="1005" alt="Screenshot 2022-03-01 at 7 32 35 PM" src="https://user-images.githubusercontent.com/22764172/156183165-0269c773-4790-4925-b4fa-a15c9ab32aab.png">

**Comment by GauravCalidig** [comment]
+1

**Comment by untillnesss** [comment]
Any updates, i had a same issue ?

**Comment by khushbu2898** [comment]
+1
