### ISSUE TITLE
run flutter build apk --release    android  platform  error

### ISSUE THREAD

**Issue by OmgKevin** [dooboolab/flutter_inapp_purchase#166]
### Version of flutter_inapp_purchase
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G84, locale zh-Hans-CN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

 
### flutter build apk --release

error：

You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce
the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              0.6s
Resolving dependencies...                                           2.6s
Running Gradle task 'assembleRelease'...                                
注: /Users/admin/flutter/.pub-cache/hosted/pub.flutter-io.cn/connectivity-0.4.6/android/src/main/java/io/flutter/plugins/connectivity/ConnectivityBroadcastReceiver.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。                                                             
注: /Users/admin/flutter/.pub-cache/hosted/pub.flutter-io.cn/easy_contact_picker-0.0.2/android/src/main/java/com/liuwei/easy_contact_picker/EasyContactPickerPlugin.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。                                                               
/Users/admin/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_inapp_purchase-2.1.2/android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java:3: 错误: 找不到符号
import androidx.annotation.Nullable;                                                                               
                          ^                                                                                        
  符号:   类 Nullable                                                                                              
  位置: 程序包 androidx.annotation                                                                                 
/Users/admin/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_inapp_purchase-2.1.2/android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java:489: 错误: 找不到符号
    public void onPurchasesUpdated(BillingResult billingResult, @Nullable List<Purchase> purchases) {              
                                                                 ^                                                 
  符号: 类 Nullable                                                                                                
注: /Users/admin/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_inapp_purchase-2.1.2/android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。                                                             
2 个错误                                                                                                           
Running Gradle task 'assembleRelease'...                                                                           
Running Gradle task 'assembleRelease'... Done                     122.7s (!)
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleRelease failed with exit code 1

**Comment by chenghui-0829** [comment]
add implementation 'androidx.annotation:annotation:1.1.0' to file build.gradle,  maybe  can solve your problem

**Comment by ZhangPingFan** [comment]
flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inapp_purchase-2.1.2/android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java

Del sth like 'Nullable' in this file and it works for me.
