### ISSUE TITLE
App store asking password on first install

### ISSUE THREAD

**Issue by oncul** [dooboolab/flutter_inapp_purchase#171]
### Version of flutter_inapp_purchase 
2.1.4
iOS - Real Device
### Steps to reproduce the behavior

When reinstall app app store asking password on init.
I didnt run any purchase functions still asking password on first install?

**Comment by daniel-hopkins** [comment]
are you calling`FlutterInappPurchase.instance.getPurchaseHistory()` on launch?
This would need a logged in user in order to know who/what to query.

**Comment by oncul** [comment]
I dont call any purchase method on launch. i think its about appstore. When app has non verified receipts, appstore kit call app to login.
Do you have any idea about this ?

**Comment by hyochan** [comment]
For pop up dialogs, you may refer to [react-native-iap issue](https://github.com/dooboolab/react-native-iap/issues/863)

**Comment by evanave** [comment]
I'm experiencing the same thing now...

I see " Purchase Successful !! " in my output when I first install and the "Sign in with Apple ID" pops up.

**Comment by vivchar** [comment]
I have the same problem, any update?

**Comment by oncul** [comment]
I found a documentation on apple developer. I think it s about finishTransaction. If you dont call finishtransaction after purchase, storekit calls updatetransaction method. 

> Transactions on the payment queue are persistent until they are completed. StoreKit calls your observer’s paymentQueue(_:updatedTransactions:) method every time your app launches or resumes from background to tell you about transactions in the queue. After you've finished processing a transaction in your app, always call the finishTransaction(_:) method to finish the transaction and remove it from the queue.

[Related Apple doc](https://developer.apple.com/documentation/storekit/skpaymentqueue/1506003-finishtransaction)
