### ISSUE TITLE
Exhausted heap space, trying to allocate 34359738384 bytes. Exception: The plugin flutter_inapp_purchase could not be built due to the issue above.

### ISSUE THREAD

**Issue by richardbonneau** [dooboolab/flutter_inapp_purchase#172]
### Version of flutter_inapp_purchase
2.1.4
### Platforms you faced the error (IOS or Android or both?)
Both
### Actual behavior
There is a memory leak since I've implemented flutter_inapp_purchase. I confirmed that the package was the issue when I got the error that's in the title. The package is trying to allocate 34gb of memory, which is insane.
### Tested environment (Emulator? Real Device?)
Both. Same behavior on both environment.

**Comment by hyochan** [comment]
I think we need more info on where this is occuring. Any logs?

**Comment by hyochan** [comment]
Looks like the [flutter issue](https://github.com/flutter/flutter/issues/23907)
