### ISSUE TITLE
getAvailablePurchases() fails on iOS

### ISSUE THREAD

**Issue by evanave** [dooboolab/flutter_inapp_purchase#173]
### Version of flutter_inapp_purchase
2.1.4

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Return list of purchased items

### Actual behavior
flutter: PlatformException(E_UNKNOWN, An unknown or unexpected error has occured. Please try again later., null)

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
`List<PurchasedItem> list = await FlutterInappPurchase.instance.getAvailablePurchases();`

Which calls...
`dynamic result = await _channel.invokeMethod('getAvailableItems');
`and fails returning PlatformException

Is anyone else having this issue?

**Comment by evanave** [comment]
It looks like this issue resolved itself by updating to Flutter 1.14.6 (I was on 1.12.13)

**Comment by davidmartos96** [comment]
@evanave Do you have any clue about what could be the reason? We have a couple of iOS users in a production app that say they the app thinks they are not subscribed, even though they are.
We don't have any way to debug this, as it is working perfectly fine for us...

**Comment by evanave** [comment]
@davidmartos96 - this issue went away for me when I upgraded Flutter from 1.12.13 to 1.14.6.
