### ISSUE TITLE
FlutterInappPurchase.instance.requestPurchase() never resolves

### ISSUE THREAD

**Issue by moritzmorgenroth** [dooboolab/flutter_inapp_purchase#174]
### Version of flutter_inapp_purchase
2.1.4

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
`await FlutterInappPurchase.instance.requestPurchase(item.productId);` should return a value after purchase completion.

### Actual behavior
The Futures never returns a value. 

### Tested environment (Emulator? Real Device?)
Pixel 3a

### Steps to reproduce the behavior
Usual setup, then await requesting the purchase. `await FlutterInappPurchase.instance.requestPurchase(item.productId);`

**Comment by hyochan** [comment]
You should register the listener to get the result. [Readme](https://github.com/dooboolab/flutter_inapp_purchase#register-listeners-to-receive-purchase) would help.

**Comment by moritzmorgenroth** [comment]
@hyochan but why return a future then if you are never resolving it? If you are not planning to return anything and have a listener in place, just void it.

**Comment by pstromberg98** [comment]
@hyochan I agree with @moritzmorgenroth here. This should be reopened to either have the Future complete with something or void the method
