### ISSUE TITLE
purchaseToken returns null when restore purchase from IOS

### ISSUE THREAD

**Issue by kalismeras61** [dooboolab/flutter_inapp_purchase#177]
### Version of flutter_inapp_purchase

Latest version

### Platforms you faced the error (IOS or Android or both?)
Tested only ios

### Expected behavior
Should be string token key
### Actual behavior
when call FlutterInappPurchase.instance.getPurchaseHistory(); in detils purchaseToken is null.

### Tested environment (Emulator? Real Device?)
Real device

**Comment by surenyonjan** [comment]
Having same problem in `2.2.0`

1. Real Device
2. Sandbox Account
3. Tested only on iOS

**Comment by doiya46** [comment]
iOS don't use `purchaseToken`, to verify iOS transaction use `purchaseItem.transactionReceipt` and following the apple document:

https://developer.apple.com/documentation/appstorereceipts/requestbody https://developer.apple.com/documentation/appstorereceipts/verifyreceipt
