### ISSUE TITLE
Why is state of Purchase.item set to "TransactionState.restored", since I haven't call finishTransactionIOS

### ISSUE THREAD

**Issue by schankam** [dooboolab/flutter_inapp_purchase#179]
### Version of flutter_inapp_purchase

2.2.0

### Platforms you faced the error (IOS or Android or both?)

IOS

### Tested environment (Emulator? Real Device?)

Real device, sandbox user

### Steps to reproduce the behavior

Hello ! I need a bit of help to understand the correct behaviour of the plugin...

I am logging my user purchases with getAvailablePurchases(), and their status is most of the time set to "TransactionState.restored". When a subscription is renewed, and I start the app, I get a new transaction (normal), and the status of this transaction is set to "TransactionState.Purchased" - If I reload my app, without doing anything (for example, without doing the server verification), the status of this purchase will be set to "TransactionState.restored". Is it a normal behaviour ? 

I thought that as long as I do not call "finishTransactionIOS", the state would stay as "TransactionState.Purchased" ? How to I differenciate transactions that I haven't treated yet compared to the one I already have ?

**Comment by jukka-palomaki** [comment]
@schankam Did you get any idea how this logic works?
