### ISSUE TITLE
iOS Crashing on getProducts. Perhaps I'm doing something wrong?

### ISSUE THREAD

**Issue by evanave** [dooboolab/flutter_inapp_purchase#18]
### Version of flutter_inapp_purchase
0.5.8 (and previous versions as well)

### Platforms you faced the error (IOS or Android or both?)
iOS Only

### Tested environment (Emulator? Real Device?)
Testing on an iPhone Device (not emulator) with WiFi access only.

### Steps to reproduce the behavior

 Whenever I call getProducts, I get a crash on execution of the code below.
```
 dynamic result = await _channel.invokeMethod(
        'getItems',
        {
          'skus': skus,
        },
      );

```
I believe its receiving the data from Apple, but it crashes with no error text. Just says loses connection to device. 

Anyone else getting this error?

Thanks for the plugin - works like a charm on Android. Can't wait to get it working for iOS as well :)

**Comment by dooboolab** [comment]
@evanave It is because you haven't given this repo a star! (just kidding). Let me find out soon.

**Comment by dooboolab** [comment]
@evanave I've just tested in my environment and everything worked fine. Could you share some of your codes? Does this look something like below?
```
final List<String>_productLists = [
    'point_1000',
    '5000_point',
  ];

  Future<Null> _getProduct() async {
    List<IAPItem> items = await FlutterInappPurchase.getProducts(_productLists);
    for (var item in items) {
      print('${item.toString()}');
      this._items.add(item);
    }

    setState(() {
      this._items = items;
    });
  }
```

**Comment by evanave** [comment]
Star given! :)

It seems I'm not calling prepare before getProducts. Unfortunately work is about to start so I don't think I'll have time to test out everything. But will get back to you ASAP.

Appreciate the quick response, most likely user error on my end :)

**Comment by evanave** [comment]
```
class IAPPageState extends State<IAPPage> {
  IAPPageState();

  String message = "Loading...";

  final List<String>_productLists = iOS()
      ? ['calc0002',]
      : ['permanent_pro_license'];

//  String _platformVersion = 'Unknown';
  List<IAPItem> _items = [];

  void goBack(){
    navigatorKey.currentState.pop(context);
  }

  @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  Future<void> initPlatformState() async {
    String platformVersion;
    // Platform messages may fail, so we use a try/catch PlatformException.
    try {
      platformVersion = await FlutterInappPurchase.platformVersion;
    } on Exception {
      platformVersion = 'Failed to get platform version.';
    }
    message = "";
    print("Platform Version $platformVersion");
    // prepare
    if (iOS()){
      print("GETTING PRODUCTS");
      var result = await FlutterInappPurchase.prepare;
      print('result: $result');
      List<IAPItem> items = await FlutterInappPurchase.getProducts(_productLists);
      for (var item in items) {
        print('${item.toString()}');
        this._items.add(item);
      }
    } else {
      print("PREPARING");
      var result = await FlutterInappPurchase.prepare;
      print('result: $result');
    }


    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    setState(() {
//      _platformVersion = platformVersion;
    });

    // refresh items for android
    if (!iOS()) {
      String msg = await FlutterInappPurchase.consumeAllItems;
      print('consumeAllItems: $msg');
      this._getProduct();
    }
  }

```
And then some debug print in the plugin...

```
static Future<List<IAPItem>> getProducts(List<String> skus) async {
    skus = skus.toList();
    if (Platform.isAndroid) {
      dynamic result = await _channel.invokeMethod(
        'getItemsByType',
        <String, dynamic>{
          'type': _typeInApp[0],
          'skus': skus,
        },
      );

      List list = json.decode(result.toString());
      List<IAPItem> products = list
          .map<IAPItem>(
            (dynamic product) =>
                new IAPItem.fromJSON(product as Map<String, dynamic>),
          )
          .toList();

      return products;
    } else if (Platform.isIOS) {
      print("GETTING IOS PLATFORM");
      dynamic result = await _channel.invokeMethod(
        'getItems',
        {
          'skus': skus,
        },
      );
      print("RESULT RECEIVED");

      result = json.encode(result);
      List list = json.decode(result.toString());
      List<IAPItem> products = list
          .map<IAPItem>(
            (dynamic product) =>
                new IAPItem.fromJSON(product as Map<String, dynamic>),
          )
          .toList();

      return products;
    }
    throw new PlatformException(code: Platform.operatingSystem);
  }
```

OUTPUT: 
flutter: Platform Version iOS 10.3.3
flutter: GETTING PRODUCTS
flutter: DIM VALUES: 0 0
flutter: Comparing ActiveInput: 0 to 0 and Order is 1 and dimensions: -1
flutter: result: true
flutter: GETTING IOS PLATFORM
Lost connection to device.
flutter: Platform Version iOS 10.3.3
flutter: GETTING PRODUCTS
flutter: result: true
flutter: GETTING IOS PLATFORM
Lost connection to device.

**Comment by dooboolab** [comment]
@evanave I was just kidding but thank you! I feel like this could be a configuration issue. Could you follow guide in my [medium post](https://medium.com/@dooboolab/flutter-in-app-purchase-7a3fb9345e2a)?

**Comment by dooboolab** [comment]
<img width="434" alt="screen shot 2018-08-20 at 11 03 27 pm" src="https://user-images.githubusercontent.com/27461460/44345083-42c11080-a4cd-11e8-9edd-53883552b3e5.png">

Also Changning bundle identifier to yours and testing in example project may help you find out the problem!

just see below code in line 18.
```
  final List<String>_productLists = Platform.isAndroid
      ? [
      'android.test.purchased',
      'point_1000',
      '5000_point',
      'android.test.canceled',
    ]
    : ['com.cooni.point1000','com.cooni.point5000'];
```

Change the second array to 
```
   : ['calc0002];
```

and try out.

**Comment by dooboolab** [comment]
@evanave Yeah please comeback after trying the example!

**Comment by evanave** [comment]
It fails when there's no introductoryPrice.

**Comment by dooboolab** [comment]
@evanave maybe it relates to issue#21. Could you try `0.6.2`?

**Comment by BadReese** [comment]
I am using 2.2.0, but get the same issue..
