### ISSUE TITLE
Unhandled Exception: PlatformException(getItemsByType, E_SERVICE_ERROR, The service is unreachable. This may be your internet connection, or the Play Store may be down.)

### ISSUE THREAD

**Issue by danielgchap** [dooboolab/flutter_inapp_purchase#182]
### Version of flutter_inapp_purchase
  flutter_inapp_purchase: ^2.2.0

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Google Play Store connect, retrieve items

### Actual behavior

'E/flutter (12504): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(getItemsByType, E_SERVICE_ERROR, The service is unreachable. This may be your internet connection, or the Play Store may be down.)
E/flutter (12504): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (12504): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (12504): <asynchronous suspension>
E/flutter (12504): #2      FlutterInappPurchase.getProducts (package:flutter_inapp_purchase/flutter_inapp_purchase.dart:103:39)
E/flutter (12504): #3      IAPManager._getProducts (package:instapray/network/iap/iap_manager.dart:99:45)'

### Tested environment (Emulator? Real Device?)
Device 

### Steps to reproduce the behavior

- Followed Medium Doc and Flutter pub example
- IAP's work fine on iOS
- Setup managed IAP's in Google play store
- Ensure that my android manifest package name matches what I have in play store
- Fire up app, attempt to connect to store, just as in example docs
- I receive the error above

**Comment by danielgchap** [comment]
This was done just with a physical device and Visual Studio code. I have not tried using a release apk through, say, the Google Play Store Beta testers channel.

**Comment by english-aha-center** [comment]
> This was done just with a physical device and Visual Studio code. I have not tried using a release apk through, say, the Google Play Store Beta testers channel.

Check if you logged to play store on your test device.
