### ISSUE TITLE
Document clearTransactionIOS API method

### ISSUE THREAD

**Issue by erf** [dooboolab/flutter_inapp_purchase#187]
Hi, i could not see the method call `clearTransactionIOS` documented in `README.md`.

Is there a reason for this, or should it be added?

BTW: Thanks for this API ! Solved my problem with the official `in_app_purchase` package.

### Version of flutter_inapp_purchase

2.2.0

**Comment by erf** [comment]
I could add this to the README.md, but would be nice to get some feedback from the author - not sure if this is an active project anymore?

**Comment by louieseno** [comment]
@erf does finishtransactionIos work for you ?

**Comment by erf** [comment]
@louieseno i use `clearTransaction`, which should call `clearTransactionIOS`, and it should work, but that is not related to this issue, or?
