### ISSUE TITLE
ios - App Store reject - title and description empty but localizedPrice exist

### ISSUE THREAD

**Issue by axilaris** [dooboolab/flutter_inapp_purchase#189]
I have a problem here:
https://stackoverflow.com/questions/62324942/flutter-in-app-flutter-inapp-purchase-ios-app-store-reject-performance-ap

### Version of flutter_inapp_purchase
flutter_inapp_purchase: ^2.2.0

### Platforms you faced the error (IOS or Android or both?)
IOS only

### Expected behavior
purchase non-consumable transacted properly

### Actual behavior
rejected AppStore -  Performance: App Completeness
title and description empty
not sure completing IOS transaction (finishTransactionIOS needed)

### Tested environment (Emulator? Real Device?)
IOS Simulator and real device

### Steps to reproduce the behavior
I have tried to use this for in app purchase. https://github.com/dooboolab/flutter_inapp_purchase https://pub.dev/packages/flutter_inapp_purchase

here is how I implemented in app, non-consumable. It works for Android but for IOS I am not sure. (I put my code here https://gist.github.com/axilaris/2b186c7a4073671128e8cacc09dfc384) but to summarize it below:

initialization part:
- initInAppPlatformState()
- _getProduct()
purchase part:
- _requestPurchase(product id)

My code is here: https://gist.github.com/axilaris/2b186c7a4073671128e8cacc09dfc384)

**Comment by srsudar** [comment]
OP's suggestion there fixed this for me--just edit the description on Appstore Connect and save it. Somehow that flushes things through Apple's shoddy system.
