### ISSUE TITLE
Didn't fetch product id

### ISSUE THREAD

**Issue by TulsiKavathiya** [dooboolab/flutter_inapp_purchase#190]
In Demo If we are change product id from 'android.test.purchased' to android.svc.purchased ,we didn't get item and also didn't fetch SKU when upload in play store in internal testing.

**Comment by dchandrani** [comment]
Same issue I am facing for android. Not able to fetch products for my product ids, only android.test.purchased is working to fetch IAPItems. Please have a look into this.
