### ISSUE TITLE
Promo code is not working in iOS 

### ISSUE THREAD

**Issue by markqq** [dooboolab/flutter_inapp_purchase#191]
### Version of flutter_inapp_purchase
flutter_inapp_purchase: ^2.2.0

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Enter promo code in App Store  ->  open the app  ->  `purchaseUpdatedSubscription` will receive a `PurchasedItem`, notify the app-backend after being validated  ->  call `finishTransactionIOS`

### Actual behavior
Enter promo code in App Store  ->  open the app  ->  `purchaseUpdatedSubscription` will not receive any data.

It works all fine through the regular transaction, but can not handle the promo code.

### Tested environment (Emulator? Real Device?)
Real Device

**Comment by jkz27** [comment]
Hey @markqq wondering if you have solves this question in the end? I am experiencing the same thing
