### ISSUE TITLE
Why are the Stream methods static (and not part of instance)

### ISSUE THREAD

**Issue by erf** [dooboolab/flutter_inapp_purchase#193]
Why are the Stream methods static (and not part of `instance`). 

That is `purchaseUpdated`, `purchaseError`, `connectionUpdated`, `purchasePromoted` and their `StreamController`. Could they not just be member variables called via the `instance` Singelton, like the other methods?

**Comment by vintage** [comment]
Same. I wouldn't even notice the stream equivalents without this comment. Didn't see it in the docs, nor the API exposed by the plugin instance.
