### ISSUE TITLE
It wont build for iOS

### ISSUE THREAD

**Issue by marcinOz** [dooboolab/flutter_inapp_purchase#194]
### Version of flutter_inapp_purchase
2.2.0

### Platforms you faced the error (IOS or Android or both?)
iOS only

### Expected behavior
it should build (like it did and work with "official" in-app purchase package).

### Actual behavior
XCode build fails with error:
```Running pod install...                                              5.1s
Running Xcode build...                                          
Xcode build done.                                           181.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inapp_purchase-2.2.0/ios/Classes/FlutterInappPurchasePlugin.m:45:52: warning: assigning to 'id<IAPPromotionObserverDelegate>' from incompatible type 'FlutterInappPurchasePlugin *__strong'
        [IAPPromotionObserver sharedObserver].delegate = self;
                                                       ^ ~~~~
    1 warning generated.
    /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inapp_purchase-2.2.0/ios/Classes/FlutterInappPurchasePlugin.m:45:52: warning: assigning to 'id<IAPPromotionObserverDelegate>' from incompatible type 'FlutterInappPurchasePlugin *__strong'
        [IAPPromotionObserver sharedObserver].delegate = self;
                                                       ^ ~~~~
    /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inapp_purchase-2.2.0/ios/Classes/FlutterInappPurchasePlugin.m:200:79: warning: implicit conversion loses integer precision: 'SKPaymentTransactionState' (aka 'enum SKPaymentTransactionState') to 'int' [-Wshorten-64-to-32]
                                                         [NSNumber numberWithInt: item.transactionState], @"transactionStateIOS",
                                                         ~                        ^~~~~~~~~~~~~~~~~~~~~
    /usr/local/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inapp_purchase-2.2.0/ios/Classes/FlutterInappPurchasePlugin.m:586:71: warning: implicit conversion loses integer precision: 'SKPaymentTransactionState' (aka 'enum SKPaymentTransactionState') to 'int' [-Wshorten-64-to-32]
                                                 [NSNumber numberWithInt: transaction.transactionState], @"transactionStateIOS",
                                                 ~                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
    3 warnings generated.
    ld: framework not found in_app_purchase
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
Encountered error while building for device.
Failed to build iOS platform, error: exit status 1
```

### Tested environment (Emulator? Real Device?)
Simulator but that doesn't have nothing to do as just build or archive results in the same.

### Steps to reproduce the behavior
Added pub package and build.

FLutter Doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.4 19E287, locale en-PL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!

**Comment by marcinOz** [comment]
When i've added `in_app_purchase: ^0.3.4` to my dependencies it works... but I tried everything flutter clear, removing Pods dir..
Had anyone similar issues?

**Comment by thize** [comment]
Same issue

**Comment by Xyz3R** [comment]
Same issue here after upgrading my flutter version. 

Flutter Doctor Output:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.6 19G2021, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by mozerrr** [comment]
Same issue
