### ISSUE TITLE
flutter: purchase-error: responseCode: null, debugMessage: SKPaymentTransactionStateFailed, code: E_USER_CANCELLED, message: Cancelled

### ISSUE THREAD

**Issue by Waheed388** [dooboolab/flutter_inapp_purchase#197]
### Version of flutter_inapp_purchase
2.2.0
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
Show in-app purchase pop-up again
### Actual behavior
The in-app purchase pop up never showed again.
### Tested environment (Emulator? Real Device?)
Real device+Sandbox account
### Steps to reproduce the behavior

Just hit the cancel button when system ask you to give a password to confirm this transaction. After that whenever I hit the purchase button I get this error message: flutter: purchase-error: responseCode: null, debugMessage: SKPaymentTransactionStateFailed, code: E_USER_CANCELLED, message: Cancelled

**Comment by markqq** [comment]
Did you use a purchase error subscription to print the `PurchaseResult`? After clicking the cancel button, the pop up won't show again until you request a new purchase, and you can use `FlutterInappPurchase.purchaseError.listen` to detect the cancelation.

**Comment by fbcouch** [comment]
Try calling `FlutterInappPurchase.finishTransactionIOS(purchasedItem.transactionId)` – the issue is that the cancelled transaction needs to have finishTransaction called on it to clear it out so the user can start a new transaction.
