### ISSUE TITLE
FR return DateTime instead of dynamic for dates

### ISSUE THREAD

**Issue by lukepighetti** [dooboolab/flutter_inapp_purchase#20]
I might be able to help with this

**Comment by lukepighetti** [comment]
Do we know what timezone these doubles are coming in as on iOS? It appears to be Central Time?

**Comment by lukepighetti** [comment]
Why is originalTransactionDateIOS = `1534870291000.0`
and transactionDate = `1534876677000.0` ?

**Comment by dooboolab** [comment]
@lukepighetti [originalTransaction](https://developer.apple.com/documentation/storekit/skpaymenttransaction/1411284-originaltransaction) is available for restore purchase and purchase of cancelled/expired subscriptions. [transactionDate](https://developer.apple.com/documentation/storekit/skpaymenttransaction/1411273-transactiondate?language=objc) is actual purchased date.

**Comment by lukepighetti** [comment]
#24

**Comment by dooboolab** [comment]
@lukepighetti Thanks so much for your hard work! I've merged this.
