### ISSUE TITLE
An Active Subscription List iOS

### ISSUE THREAD

**Issue by foreg** [dooboolab/flutter_inapp_purchase#202]
### Version of flutter_inapp_purchase
2.2.0
### Platforms you faced the error (IOS or Android or both?)
iOS
### Tested environment (Emulator? Real Device?)
Real Device

### Question
Is there a way to get an active subscription list on iOS?

**Comment by hcaz** [comment]
getAvailablePurchases should only return active and non-consumed iaps

**Comment by foreg** [comment]
Correct me if i'm wrong, but comments on `getAvailablePurchases` in source code (v2.2.0) says

> /// Get all non-consumed purchases made on `Android` and `iOS`.
> ///
> /// This is identical to [getPurchaseHistory] on `iOS`

Comments on `getPurchaseHistory` says
> /// Retrieves the user's purchase history on `Android` and `iOS` regardless of consumption status.
> ///
> /// Purchase history includes all types of products.
> /// Identical to [getAvailablePurchases] on `iOS`.

Therefore I conclude that on iOS I can't get only active subscriptions using `getAvailablePurchases`

**Comment by shovelmn12** [comment]
Just been searching for this one as well...
how can we find out if the subscription is still valid?

**Comment by ryanbliss** [comment]
@foreg is correct as far as I can tell. In the source code, the method on `getAvailablePurchases` displays the same as for `getPurchaseHistory`, which is as follows:
```dart
if (_platform.isAndroid) {
      // Android code
} else if (_platform.isIOS) {
      dynamic result =
          await _channel.invokeMethod('getAvailableItems');

      return extractPurchased(json.encode(result));
}
```

The comment in the getPurchaseHistory does suggest that it doesn't care about consumption status. Can we get some confirmation on this?

**Comment by dipinarora9** [comment]
Hey @foreg ,
You can use this function
https://github.com/dooboolab/flutter_inapp_purchase/blob/master/lib/flutter_inapp_purchase.dart#L494

**Comment by ventr1x** [comment]
> Hey @foreg ,
> You can use this function
> https://github.com/dooboolab/flutter_inapp_purchase/blob/master/lib/flutter_inapp_purchase.dart#L494

No you cannot. This function has subscription settings hardcoded into it and randomly returns true on Android without any checks.
For real updates you're supposed to use server-to-server API which are available on both platforms. This is also true for native development, so all these questions are quite annoying and should not be in github issues.
