### ISSUE TITLE
Handlers get too many states

### ISSUE THREAD

**Issue by xafgun** [dooboolab/flutter_inapp_purchase#203]
### Version of flutter_inapp_purchase
2.2.0
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Handlers get 1 state after purchase is success or error.
### Actual behavior
Handlers get 10+ state
### Tested environment (Emulator? Real Device?)
Real Device

![WhatsApp Image 2020-07-23 at 21 15 57](https://user-images.githubusercontent.com/2115846/88325346-a85b4e80-cd2d-11ea-9dce-e16889545638.jpeg)

**Comment by doiya46** [comment]
Same issue, I handle verify receipt by server and see a lot of request at the same time
