### ISSUE TITLE
If Flutter Firebase Messaging is support, occur Error "IAP not prepared. Check if Google Play service is available".

### ISSUE THREAD

**Issue by hukusuke1007** [dooboolab/flutter_inapp_purchase#209]
### Version of flutter_inapp_purchase
2.2.0

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Show IAP dialog.

### Actual behavior
Not show IAP dialog and occur Error.

```
IAP not prepared. Check if Google Play service is available.
```

### Tested environment (Emulator? Real Device?)
Android: Emulator and Real Devices

### Steps to reproduce the behavior
1. FlutterInappPurchase.instance.initConnection
-> result is "Billing client ready"
2. FlutterInappPurchase.instance.getSubscriptions
3. FlutterInappPurchase.instance.requestSubscription
-> throw exception.

### Enviroment
```
$ flutter --version
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (3 days ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1
```

### Additional Comments
This issue is depended on the Flutter Firebase Messaging.
Version.
```
firebase_messaging: 6.0.16
```

**Comment by hukusuke1007** [comment]
If Background Message(Firebase Messaging Plugins) is support, it occur issue.If Background Message not support, it's not occur issue.

https://pub.dev/packages/firebase_messaging

```kotlin
package io.flutter.plugins.firebasemessagingexample

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService

class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingService.setPluginRegistrant(this)
    }

    override fun registerWith(registry: PluginRegistry?) {
        GeneratedPluginRegistrant.registerWith(registry)
    }
}
```

AndroidManifest.xml
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.xxxx.xxxx.xxx">
    <application
        android:name=".Application"
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher">
```

**Comment by arslancreo** [comment]
did someone find a solution for it?
