### ISSUE TITLE
New features to acquire and retain subscribers

### ISSUE THREAD

**Issue by uzumaki258** [dooboolab/flutter_inapp_purchase#211]
### Version of flutter_inapp_purchase
`flutter_inapp_purchase: ^2.2.0`
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
New features to acquire and retain subscribers.
On November 1, 2020, account hold and subscription restore will become mandatory. Subscription pause and resubscribe will also be enabled for all apps.

![image](https://user-images.githubusercontent.com/26773292/91158876-7acd4080-e6f1-11ea-83bb-0631c49d95b4.png)
For more detail please check it:
https://android-developers.googleblog.com/2020/06/new-features-to-acquire-and-retain-subscribers.html
### Actual behavior
Now flutter_inapp_purchase don't allow to do this, I hope this package will update soon to adapt the new Google Play policy.
Thank you.

**Comment by pinpong** [comment]
Hi,

any news?

**Comment by uzumaki258** [comment]
I think we should use server-side verification for this Featured.
