### ISSUE TITLE
Question iOS Tesing App subscription very slow

### ISSUE THREAD

**Issue by doiya46** [dooboolab/flutter_inapp_purchase#218]
### iOS IAP

1. Install app through TestFlight
2. Test 40 times subscriptions in an Apple Account (Because we have a lot of releases version)
3. Click to buy a Subscription very slow (2 to 3 minutes and maybe it not show dialogue to purchase, it will receive 3 or 4 old transactions in purchaseUpdatedListener) 

How can I resolve this problem?

**Comment by Abosrie** [comment]
I am experiencing the same issue! Have you found a solution?

**Comment by doiya46** [comment]
> I am experiencing the same issue! Have you found a solution?

No, I haven't :(

**Comment by sanekyy** [comment]
Same issue with very slow work and same issue with  "receive 3 or 4 old transactions in purchaseUpdatedListener"
