### ISSUE TITLE
Cannot handle pending - slow card purchases

### ISSUE THREAD

**Issue by Zeynal7** [dooboolab/flutter_inapp_purchase#221]
### Version of flutter_inapp_purchase
2.2.0
### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior

All of my purchases are consumables

If I use slow card & close the app and after a while, after the card is approved, if I open the app:
1) I get all of the purchases with `getPurchaseHistory()` 
1.2) I don't use `getAvailablePurchases` because it returns empty list every time, therefore I use getPurchaseHistory
2) check the purchases that are not acknowledged (`isAcknowledgedAndroid == false`) and `purchaseStateAndroid` is 0 
3) Then I should try to verify these purchases. 

### Actual behavior

All of the purchases that I get with getPurchaseHistory has isAcknowledgedAndroid as null and almost all other fields are null.
Only fields with real data are product ids, purchase token etc.

### Tested environment (Emulator? Real Device?)

Real Device

### Steps to reproduce the behavior

1) Buy with slow card
2) Close the app
3) Open after purchase is verified.
4) Get the purchases. that are  not acknowledged and verify and consume them.

Or if anyone knows, please let me know how to handle pending purchases with this package.
Note: I am using backend server to verify the purchases. All of my codes are on the backend and I don't use verify receipt function of this package. So I need to have a way of knowing which purchases are pending, and verify them myself.

**Comment by Zeynal7** [comment]
Or if anyone knows, please let me know how to handle pending purchases with this package.

**Comment by srsudar** [comment]
What did you find on this? I'm seeing null values for `isAcknowledgedAndroid` as well as most other fields, and I'm not sure why.
