### ISSUE TITLE
No responses from requestSubscription and getAvailablePurchases

### ISSUE THREAD

**Issue by Swepilot** [dooboolab/flutter_inapp_purchase#228]
### Version of flutter_inapp_purchase
2.2.0

### Platforms you faced the error (IOS or Android or both?)
Only tested on iOS

### Expected behavior
`FlutterInappPurchase.instance.requestSubscription` to bring up the AppStore IAP dialogue

### Actual behavior
`FlutterInappPurchase.instance.requestSubscription` brings up the AppStore IAP dialogue only some times, at random and after long delay sometimes. When the dialogue does show I am able to complete the purchase and it later renews 5 times as expected.

Same with `FlutterInappPurchase.instance.getAvailablePurchases()`. Sometimes it returns, sometimes it doesn't

`FlutterInappPurchase.instance.getSubscriptions` returns the list of subscriptions every time, without problem.

### Tested environment (Emulator? Real Device?)
Real iPad with iOS 14.0 in Sandbox 

### Steps to reproduce the behavior
Using the example code as is.

**Comment by LSFMint** [comment]
Hi, is it anyway to solve this issue? I encounter this issue on Xcode 12 with iOS 14

**Comment by spedalilama** [comment]
I am encountering the same issue, any status on the fix for this?

**Comment by sanekyy** [comment]
Same issue. It works but very slow.

**Comment by hamidAslami** [comment]
> I am encountering the same issue, any status on the fix for this?

me too

**Comment by d9media** [comment]
I think I'm seeing the same

**Comment by Joyker** [comment]
same problem, any solution ?
