### ISSUE TITLE
 [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'int' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by dipinarora9** [dooboolab/flutter_inapp_purchase#230]
### Steps to reproduce the behavior
Try calling `List<IAPItem> items = await FlutterInappPurchase.instance.getSubscriptions(['product_id']);`

**Comment by neestell** [comment]
The bug  isn't fixed in 2.3.1

**Comment by dipinarora9** [comment]
Hi @neestell , @hyochan hasn't pushed the fix on pub.dev yet.

**Comment by hyochan** [comment]
I think I did. I'll just try to publish the something to 2.3.2 and please test that out too.

**Comment by dipinarora9** [comment]
Okay, the new version is working as expected.

**Comment by sharmavishal914** [comment]
Hi @hyochan 
Please let me know once you push 2.3.2, I am facing same issue

**Comment by sharmavishal914** [comment]
Thanks guys

**Comment by hyochan** [comment]
> Hi @hyochan 
> Please let me know once you push 2.3.2, I am facing same issue

I just did!

**Comment by edsonboldrini** [comment]
I pick the version 2.3.2 and the fix was not there, I only see this fix on master, please re-tag the lib.
