### ISSUE TITLE
Unknown error still persists (others closed by bot for nothing)

### ISSUE THREAD

**Issue by saarikivit** [dooboolab/flutter_inapp_purchase#235]
### Version of flutter_inapp_purchase
2.3.2 and 2.1.5 give the same results
(flutter 1.22.x)
(iOS 13.3.1)

### Platforms you faced the error (IOS or Android or both?)
iOS did not test Android

### Expected behavior
To handle purchase

### Actual behavior
Throw unknown error

### Tested environment (Emulator? Real Device?)
Real device hooked to a computer. Testflight or App center not tested!

### Steps to reproduce the behavior
**1. Run**
  await FlutterInappPurchase.instance.initConnection;

**2. Run**
await FlutterInappPurchase.instance.getSubscriptions(
        productIds,
      );
**OR**
await FlutterInappPurchase.instance.getProducts(
        productIds,
      );

**3. Run**
  await FlutterInappPurchase.instance.requestSubscription(
      productId,
    );
**OR**
  await FlutterInappPurchase.instance.requestPurchase(
      productId,
    );

They both yield the same results:
`responseCode: null, debugMessage: SKPaymentTransactionStateFailed, code: E_UNKNOWN, message: An unknown or unexpected error has occured. Please try again later.`

**Comment by Dhaval2404** [comment]
Facing the same issue. 😥

**Comment by Dhaval2404** [comment]
This seems to be a device-specific issue. Try reset settings and use a new tester account. Should work fine after that.

**Comment by Bennik2000** [comment]
Although it was stated in the issue I want to leave a note for my future self: 
In app purchases only work on a real device. Not a simulator!

**Comment by henry2man** [comment]
@saarikivit  Also please check that you've signed all Paid Apps agreements on App Store Conect: https://appstoreconnect.apple.com/agreements/#/ 

I was facing lots of errors until I realized that I haven't signed agreements. Hope this helps!

**Comment by victorandeloci** [comment]
Well... I was facing the same issue for weeks. I've started using **flutter_inapp_purchase** (where I found this error) and then I've migrated to **in_app_purchase** (where I another error with UNKNOWN_ERROR_CODE). It seems that both packages's errors are the same. They are related with the test enviroment... 

I've solved this by registering an account on the sandbox test environment of the app and testing the purchase with this account. I've **NOT** tested this in **flutter_inapp_purchase**... but I really think they are related

Hope it helps

**Comment by saarikivit** [comment]
> @saarikivit  Also please check that you've signed all Paid Apps agreements on App Store Conect: https://appstoreconnect.apple.com/agreements/#/ 
> 
> I was facing lots of errors until I realized that I haven't signed the agreements. Hope this helps! 

These were not the problem as I had a same-kind-of working setup with revenuecat's package: purchases_flutter.

**Comment by rostopira** [comment]
With sandbox and debug I do not have this error.
However I can't pass App Store review, because they get this error for some reason

**Comment by vytautas-pranskunas-** [comment]
Has anyone solved this? 
I have similar issue just with prompt to sign in: https://github.com/dooboolab/flutter_inapp_purchase/issues/285
