### ISSUE TITLE
[iOS] SKPaymentTransactionStateFailed - An unknown or unexpected error has occured. Please try again later.

### ISSUE THREAD

**Issue by vinothvino42** [dooboolab/flutter_inapp_purchase#236]
### Version of flutter_inapp_purchase
version 2.3.2

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
I'm expecting to buy IAP item after providing password in the confirm purchase dialog.

### Actual behavior
It ask me two times for entering password (2 confirm purchase alert dialog) when requesting for purchase, after entering the password (2 times) it shows an exception `flutter: purchase-error: responseCode: null, debugMessage: SKPaymentTransactionStateFailed, code: E_UNKNOWN, message: An unknown or unexpected error has occured. Please try again later.` and I got similar issues when using official [in-app purchase](https://pub.dev/packages/in_app_purchase) plugin`SKErrorDomain - {NSLocalizedDescription: Cannot connect to iTunes Store}`

### Tested environment (Emulator? Real Device?)
Real Device (iPhone 5s)

### Steps to reproduce the behavior
Just buying an IAP flow only. Last week it worked fine, but today it's not working as expected. I've tried many solutions. I tried **neilc** solution in this thread https://developer.apple.com/forums/thread/90594. Still I'm facing this issue and also I'm using only the Testing account (which is not an apple account, just created a new gmail account and created sandbox tester account in the apple appstoreconnect)

I'm looking for the working solution asap. Thank you.

**Comment by leean912** [comment]
Same here, I have this issue since last Friday. Before that it works just fine. 

purchase-error: responseCode: null, debugMessage: SKPaymentTransactionStateFailed, code: E_UNKNOWN, message: An unknown or unexpected error has occured. Please try again later.

**Comment by louieseno** [comment]
@leean912  do you have any workaround for this issue?

**Comment by leean912** [comment]
@louieseno Currently it will only work on Test Flight, I am still unable to perform iap in local.

**Comment by ccfiel** [comment]
we have the same problem any idea how to resolve this?

**Comment by thinhlifetechvn** [comment]
Now, It work  to perform iap in local .

**Comment by vinothvino42** [comment]
> Now, It work to perform iap in local .

Your iOS version?

**Comment by vinothvino42** [comment]
@thinhlifetechvn Yeah, Looks like it's working fine now.

**Comment by thinhlifetechvn** [comment]
> > Now, It work to perform iap in local .
> 
> Your device iOS version?

13.x . I testing on ios 14.x
