### ISSUE TITLE
Android: Downloadable version from website in addition to Play Store?

### ISSUE THREAD

**Issue by joshipucher** [dooboolab/flutter_inapp_purchase#241]
Hello.

Do you know if it is possible / allowed to offer two versions of an android app:

- One that is downloadable from the Google Play Store that accepts only in-app purchases via the Google Play Store (as it is provided by the terms)
- One that is downloadable from my website that offers other payment methods for in-app purchases like Stripe or Paypal.

Thank you.

**Comment by dipinarora9** [comment]
Irrelevant issue, closing.
