### ISSUE TITLE
transactionID goes up even if transactionReceipt stays the same

### ISSUE THREAD

**Issue by lukepighetti** [dooboolab/flutter_inapp_purchase#25]
I noticed that when doing `.getPurchaseHistory()` on iOS, the `transactionID` field seems to change over time even if the receipt is the same. 

Perhaps we should present the first 24 characters of the `transactionReceipt` as the ID moving forward?

(Am I missing something?)

**Comment by lukepighetti** [comment]
I just noticed that `transactionReciept` is changing too... is this a Sandbox thing or am I misunderstanding something? 

I would expect the `transactionReceipt` and `transactionID` to never change for a transaction...?

**Comment by lukepighetti** [comment]
<img width="716" alt="screen shot 2018-08-22 at 10 11 58 am" src="https://user-images.githubusercontent.com/666539/44468728-e3115500-a5f3-11e8-86e9-6a59ba27569c.png">

**Comment by dooboolab** [comment]
@lukepighetti That is expected in ios. If you see the [link], 
```
This value corresponds to the transaction’s transactionIdentifier property.

For a transaction that restores a previous transaction, this value is different from the transaction identifier of the original purchase transaction. In an auto-renewable subscription receipt, a new value for the transaction identifier is generated every time the subscription automatically renews or is restored on a new device.
```
https://developer.apple.com/library/archive/releasenotes/General/ValidateAppStoreReceipt/Chapters/ReceiptFields.html

**Comment by lukepighetti** [comment]
@dooboolab working in Android, limited testing, simple stuff. Let me know what you think

**Comment by lukepighetti** [comment]
Thank you!
