### ISSUE TITLE
purchase updates shows wrong info

### ISSUE THREAD

**Issue by CripyIce** [dooboolab/flutter_inapp_purchase#250]
### Version of flutter_inapp_purchase
3.0.1
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
When listening to `purchaseUpdated` I should get updates based on user's real actions with Apple IAP dialog.
### Actual behavior
`purchaseUpdated` get called multiple times and always returns `transactionStateIOS = TransactionState.purchased` even when IAP dialog don't show up (which is also a bug).
### Tested environment (Emulator? Real Device?)
Real Device - iPhone 11 Pro - iOS 14.3
### Steps to reproduce the behavior
Implement basic usage of IAP

**Comment by henry2man** [comment]
@CripyIce  I've faced similar problems because I was registering listeners more than once.

Please check your code flow and check that you're registering listeners only once.

Hope this helps

**Comment by ngoryachev** [comment]
Same issue. Getting false purchase-updated event while there wasn't even system IAP dialog. Also iPhone=11 and IOS=14

**Comment by ngoryachev** [comment]
> @CripyIce I've faced similar problems because I was registering listeners more than once.
> 
> Please check your code flow and check that you're registering listeners only once.
> 
> Hope this helps

FYI i checked and i don't have set-listener duplications in my code. So maybe guess is wrong.

**Comment by SR-INGENIOUSMINDSLAB** [comment]
I am getting same issue. I have used example code and I have purchased Subscription. even after Subscription cancel or Expired It's showing only TransationState.purchase
