### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method initConnection on channel flutter_inapp)

### ISSUE THREAD

**Issue by vignesh7501** [dooboolab/flutter_inapp_purchase#251]
### Version of flutter_inapp_purchase
^3.0.1

### Platforms you faced the error (IOS or Android or both?)
Android

### Tested environment (Emulator? Real Device?)
Real Device

E/flutter (11116): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method initConnection on channel flutter_inapp)
E/flutter (11116): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (11116): <asynchronous suspension>
E/flutter (11116): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)

**Comment by caseyryan** [comment]
This is a typical problem when someone installs any plugin but does not run a full app build again. The plugin part does not support hot reload so always stop the app and build it again when you see this error

**Comment by vignesh7501** [comment]
Thank you!
