### ISSUE TITLE
FlutterInappPurchase.purchaseUpdated is never called on iOS event though native dialog says the purchase is successful

### ISSUE THREAD

**Issue by caseyryan** [dooboolab/flutter_inapp_purchase#253]
### Version of flutter_inapp_purchase
FlutterInappPurchase.purchaseUpdated.listen(
      (value) {
        print('PURCHASE UPDATED');
      },
      onDone: _onDone,
    );

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Callback is triggered

### Actual behavior
Nothing happens

### Tested environment (Emulator? Real Device?)
Real device with Sandbox account

### Steps to reproduce the behavior

I simply subscribe to the stream like this 

```dart
FlutterInappPurchase.purchaseUpdated.listen(
      (value) {
        print('FFFFFFFFFFF');
      },
    );
```

then buy a test product like so:
```dart
FlutterInappPurchase.instance.requestPurchase(
        item.productId,
      );
```

The product is successfully bought and I see a native dialog informing me of a successful buy but the 
stream callback if never triggered

**Comment by FickleLife** [comment]
I have the exact same issue. I have called `getPurchaseHistory()` and can see the sandbox purchase in there too.

**Comment by janosdupai** [comment]
At the dispose part add: 

`super.dispose()`

if you have existing issue, call this:

```
if (_conectionSubscription != null) {
      _conectionSubscription.cancel();
      _conectionSubscription = null;
    }
```

I guess, the code did not close the previous connection, that's why it give back a fake "successful" message.

**Comment by caseyryan** [comment]
> At the dispose part add:
> 
> `super.dispose()`
> 
> if you have existing issue, call this:
> 
> ```
> if (_conectionSubscription != null) {
>       _conectionSubscription.cancel();
>       _conectionSubscription = null;
>     }
> ```
> 
> I guess, the code did not close the previous connection, that's why it give back a fake "successful" message.

It has nothing to do with the issue

**Comment by janosdupai** [comment]
> > At the dispose part add:
> > `super.dispose()`
> > if you have existing issue, call this:
> > ```
> > if (_conectionSubscription != null) {
> >       _conectionSubscription.cancel();
> >       _conectionSubscription = null;
> >     }
> > ```
> > 
> > 
> > I guess, the code did not close the previous connection, that's why it give back a fake "successful" message.
> 
> It has nothing to do with the issue

Then what should I do with the subscription method? Change the pub? Or do you have any advice?

**Comment by caseyryan** [comment]
> > > At the dispose part add:
> > > `super.dispose()`
> > > if you have existing issue, call this:
> > > ```
> > > if (_conectionSubscription != null) {
> > >       _conectionSubscription.cancel();
> > >       _conectionSubscription = null;
> > >     }
> > > ```
> > > 
> > > 
> > > I guess, the code did not close the previous connection, that's why it give back a fake "successful" message.
> > 
> > 
> > It has nothing to do with the issue
> 
> Then what should I do with the subscription method? Change the pub? Or do you have any advice?

Canceling subscriptions is a must, of course, and you should really cancel them when they are not necessary anymore. But in this case the issue happens inside platform code and is surely not related to the dart side

**Comment by KyawSoeW1n** [comment]
Any solution for that one ?
