### ISSUE TITLE
Call the getAvailablePurchases method for the second time error

### ISSUE THREAD

**Issue by charleyzhu** [dooboolab/flutter_inapp_purchase#254]
### Version of flutter_inapp_purchase
any
### Platforms you faced the error (IOS or Android or both?)
iOS
### Expected behavior
get  unfinish Transaction
### Actual behavior
Call the getAvailablePurchases method for the second time
### Tested environment (Emulator? Real Device?)
any iOS Drivces
### Steps to reproduce the behavior
Call the getAvailablePurchases method for the second time

`-(void)paymentQueueRestoreCompletedTransactionsFinished:(SKPaymentQueue *)queue {  ////////   RESTORE
    NSLog(@"\n\n\n  paymentQueueRestoreCompletedTransactionsFinished  \n\n.");
    NSMutableArray* items = [NSMutableArray arrayWithCapacity:queue.transactions.count];
    
    for(SKPaymentTransaction *transaction in queue.transactions) {
        if(transaction.transactionState == SKPaymentTransactionStateRestored
           || transaction.transactionState == SKPaymentTransactionStatePurchased) {
            [self getPurchaseData:transaction withBlock:^(NSDictionary *restored) {
                [items addObject:restored];
                [[SKPaymentQueue defaultQueue] finishTransaction:transaction];     <-------------I don't understand why the business is done here.
            }];
        }
    }
    
    if (flutterResult != nil) {
        flutterResult(items);
    }
    flutterResult = nil;
}`

**Comment by teaplant** [comment]
same

**Comment by Kabariya** [comment]
@charleyzhu  @teaplant 
Hi, I am getting same issue, it is being called many times

Any fix?
