### ISSUE TITLE
Restoration of purchases if they were made on another platform

### ISSUE THREAD

**Issue by AlexShavkunov** [dooboolab/flutter_inapp_purchase#262]
Hi! I am interested in this question - How to restore purchases if made on another platform?

For example, a user makes a subscription on Android, after which he decides to continue working on iOS. And then the question arises - Is it possible using methods getAvailablePurchases() or getPurchaseHistory() to restore past purchases from another platform? Or maybe there are other ways to restore the correct purchases?

Please tell me how do you deal with this problem?

**Comment by henry2man** [comment]
You'll need to use your own backend to do this. If you check the examples there is a "verify" method that you should use to verify and confirm the purchase on your own backend.

For example in this article you'll find some tips to check purchases using Firebase Cloud Functions https://danreynolds.ca/tech/2020/12/02/Flutter-Google-Billing/
