### ISSUE TITLE
Example Implementation

### ISSUE THREAD

**Issue by srsudar** [dooboolab/flutter_inapp_purchase#263]
(This isn't really an issue, sorry dooboolab.)

There is a lot to get right in managing In-App Purchases (IAPs). This plugin has been a huge help. Nevertheless, I still found it a bit confusing. I'm preparing to release IAPs for my own app, and I thought I would share what I have. 

It is available at [srsudar/iap_manager](https://github.com/srsudar/iap_manager).

The `README.md` and the tests show some basic usage. So far it has worked for all of my test usage, although again, I still haven't tried it in production. Plenty of rough spots here and there. I also don't use consumables in my app, so I haven't implemented those at this point.

If people want to try it and validate that it works for them (or note bugs), that would be great. In the meantime, people that are just getting started might still find it useful to look at.

**Comment by AmitabhWork** [comment]
can you share a fully working example based on your code?

**Comment by srsudar** [comment]
A sample app? That is a good idea. I don't have one handy at the moment unfortunately. I'm not sure how dooboolab got his working with sample IAP items like he managed to do.

[The tests](https://github.com/srsudar/iap_manager/blob/master/test/src/iap-manager_test.dart) will give you some idea of how I think the code is meant to work. It's running in my own app in production successfully, though I'd believe there are other ways people build apps that make it not-obvious how to integrate.

If you have any questions let me know and I'll try to answer them.
