### ISSUE TITLE
not support flutter sdk 2.0.0

### ISSUE THREAD

**Issue by gongqinjing** [dooboolab/flutter_inapp_purchase#266]
This is a very useful In-App Purchase plugin, which I personally find much simpler and richer to use than the official one. But the current version can not support 2.0.0 SDK, hope to update, please

**Comment by hyochan** [comment]
Done from `4.0.0`! Thanks for the report.

**Comment by gongqinjing** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        So fast!! Thank you for your contribution！👍👍👍
        
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                gongqinjing
                            
                    
                        
                            
                                    gongqinjing@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 03/4/2021 17:41，Hyo<notifications@github.com> wrote： 



Done from 4.0.0! Thanks for the report.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
