### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by ingmferrer** [dooboolab/flutter_inapp_purchase#267]
Thanks for the great package!

Do you plan to make a null safe update of the package?

**Comment by hyochan** [comment]
Can you provide more information how to accomplish this?

**Comment by hyochan** [comment]
Can you provide more information how to accomplish this?

**Comment by ingmferrer** [comment]
https://dart.dev/null-safety/migration-guide

**Comment by Zamorite** [comment]
Thank you for bringing this up, @ingmferrer.
I would make a PR soon which I hope should give a good headstart on the null-safety migration, @hyochan

**Comment by Zamorite** [comment]
Please, let me know if I could help speed this up in any other way, @hyochan . 🙏🏽
