### ISSUE TITLE
transactionReceipt deprecated since iOS 7.0

### ISSUE THREAD

**Issue by holyspidoo** [dooboolab/flutter_inapp_purchase#27]
Should we be worried about transactionReceipt being deprecated?

`....pub-cache/hosted/pub.dartlang.org/flutter_inapp_purchase-0.6.4/ios/Classes/FlutterInappPurchasePlugin.m:257:36: 'transactionReceipt' is deprecated: first deprecated in iOS 7.0 - Use -[NSBundle appStoreReceiptURL]`

**Comment by dooboolab** [comment]
@holyspidoo Currently no! But could be updated and some PR will be welcomed!
