### ISSUE TITLE
requestSubscription future never completes

### ISSUE THREAD

**Issue by Hmendez24** [dooboolab/flutter_inapp_purchase#276]
### Version of flutter_inapp_purchase
5.0.0

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Future completes or throws exception.

### Actual behavior
Never completes

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
Simply await on `requestSubscription()`. Note: I did successfully receive `PurchaseItem` from `purchaseUpdated` stream.

I believe the issue is in the native code file `FlutterInappPurchasePlugin.m` where `FlutterResult` is not being called for that method call. Would probably need to be added for the error case as well if this indeed is the fix.

```
else if ([@"buyProduct" isEqualToString:call.method]) {
        NSString* identifier = (NSString*)call.arguments[@"sku"];
        SKProduct *product;

        for (SKProduct *p in validProducts) {
            if([identifier isEqualToString:p.productIdentifier]) {
                product = p;
                break;
            }
        }
        if (product) {
            SKMutablePayment *payment = [SKMutablePayment paymentWithProduct:product];
            [[SKPaymentQueue defaultQueue] addPayment:payment];
            result(@"Payment added"); // FUTURE COMPLETED WHEN I ADDED THIS
        } else {
            NSDictionary *err = [NSDictionary dictionaryWithObjectsAndKeys:
                                 @"Invalid product ID.", @"debugMessage",
                                 @"E_DEVELOPER_ERROR", @"code",
                                 @"Invalid product ID.", @"message",
                                 nil
                                 ];
            NSString* result = [self convertDicToJsonString:err];
            [self.channel invokeMethod:@"purchase-error" arguments:result];
        }
    }
```

**Comment by BaranMichal25** [comment]
I also encountered this bug.
In my case it happens when there is an error during requesting subscription - method `requestSubscription` never returns, but the error stream emits a value.
Temporary workaround for that is to use `then` instead of `awaiting` for the `requestSubscription` method.
