### ISSUE TITLE
In Apple In-App Purchase After redeem offer code from which function I will get response? What is the exact output I get?

### ISSUE THREAD

**Issue by amitkparekh5** [dooboolab/flutter_inapp_purchase#281]
### Version of flutter_inapp_purchase
4.0.0
### Platforms you faced the error (IOS or Android or both?)
IOS
### Tested environment (Emulator? Real Device?)
Real Device
### Steps to reproduce the behavior

Will this help??
_promotedSubscription = FlutterInappPurchase.purchasePromoted.listen((event) {
      // What will be the event ?
    });

**Comment by louna-akkad** [comment]
are  you able to redeem offer code ?
