### ISSUE TITLE
iOS Subscription Renewal Issue

### ISSUE THREAD

**Issue by jersocOD** [dooboolab/flutter_inapp_purchase#286]
### Version of flutter_inapp_purchase
3.0.1

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Get a new receipt after the renewal period.
### Actual behavior
Doesn't get a new receipt through the Apple API nor on the device.
### Tested environment (Emulator? Real Device?)
Tested on an iPhone 6 real device with real subscriptions.
### Steps to reproduce the behavior

First of all, thanks for creating such an amazing package. 

I implemented auto-renewable subscriptions for my app, on iOS and Android.
For that, I created my own API for billing that retrieves receipts and validates with Google and Apple servers.
When the user opens the app, it checks with my API if his subscription is valid using the receipt previously saved when the user purchased the first time.
It's working fine on Android as I get new receipts using their API. On the other hand, on iOS I have trouble with subscriptions since I don't have a way to get the new receipt after the renewal.

Please, any help will be appreciated.

**Comment by ascott18** [comment]
If you send an old receipt to Apple's /verifyReceipt, it still returns to you the latest state of that transaction and subscription.
