### ISSUE TITLE
FlutterInappPurchase.instance.getAvailablePurchases() returns all identical items

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [dooboolab/flutter_inapp_purchase#287]
### Version of flutter_inapp_purchase
5.0.1

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
should return items with different transactionReceipt and originalTransactionIdentifierIOS

### Actual behavior
All purcases has same transactionReceipt and originalTransactionIdentifierIOS

### Tested environment (Emulator? Real Device?)
Device

### Steps to reproduce the behavior
Make few purchases and invoke FlutterInappPurchase.instance.getAvailablePurchases()

**Comment by vgula** [comment]
Can we have an answer here please?

**Comment by vytautas-pranskunas-** [comment]
Yes, thats how iOS works. I had to refactor whole flow because of this. iOS returns one receipt for any purchases and by this receipt you can fetch all your past purchases.... Android is different - it returns different id for each purchase.

**Comment by yunchiri** [comment]
> Yes, thats how iOS works. I had to refactor whole flow because of this. iOS returns one receipt for any purchases and by this receipt you can fetch all your past purchases.... Android is different - it returns different id for each purchase.

how to solve?
