### ISSUE TITLE
getSubscriptions stopped working from one day to another

### ISSUE THREAD

**Issue by Gambolico** [dooboolab/flutter_inapp_purchase#294]
### Version of flutter_inapp_purchase

5.0.1

### Platforms you faced the error (IOS or Android or both?)

Only tested on Android

### Expected behavior

getSubscriptions() returns all the subscriptions configured in google console.

### Actual behavior

getSubscriptions() gets stuck and doesnt return anything

### Tested environment (Emulator? Real Device?)

Real device

### Steps to reproduce the behavior

I dont really know, one day worked, the next day it stopped working and this is the second day that it doesnt fetch items correctly.

### Flutter doctor

[√] Flutter (Channel stable, 2.2.2, on Microsoft Windows [VersiÃ³n 10.0.19042.1052], locale es-ES)
    • Flutter version 2.2.2 at C:\src\flutter
    • Framework revision d79295af24 (3 weeks ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Mikel\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2.4
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.57.1)
    • VS Code at C:\Users\Mikel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • ONEPLUS A5010 (mobile) • 63be0fb9 • android-arm64  • Android 9 (API 28)
    • Chrome (web)           • chrome   • web-javascript • Google Chrome 91.0.4472.124
    • Edge (web)             • edge     • web-javascript • Microsoft Edge 91.0.864.59

• No issues found!

**Comment by Gambolico** [comment]
If you guys need any more info ask me for it

**Comment by Gambolico** [comment]
is there a way to check the state of the connection to google? I didnt change the code nor the google console configuration, yet it stopped working. I think might be a connecting to google issue more than changes in the code. Please help.

**Comment by korosiadam99** [comment]
Same for me with flutter_inapp_purchase and in_app_purchase too . Is there any solution?

**Comment by Gambolico** [comment]
> Same for me with flutter_inapp_purchase and in_app_purchase too . Is there any solution?

I had billing dependency from Google put in the build.gradle, and it looks like it made a conflict with the package. I created an issue here: https://github.com/dooboolab/flutter_inapp_purchase/issues/296#issue-933398513

If you have it, delete the dependency `com.android.billingclient:billing:$version` from build.gradle.

Have a good one

**Comment by Gambolico** [comment]
@corrosionadam99 did this solve it for you? If so, please tell in the other issue I mentioned (#296) that you would also like to put a disclaimer in the readme.
