### ISSUE TITLE
[SUGGESTION] Add disclaimer for conflict with Google Billing library dependency

### ISSUE THREAD

**Issue by Gambolico** [dooboolab/flutter_inapp_purchase#296]
### Version of flutter_inapp_purchase

5.0.1

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

Added the Google Billing library to build.gradle following the tutorial from Google, and expected the plugin to work normally

### Actual behavior

Plugin completely stopped working (didnt connect, nor fetch items, purchaseHistory...)

### Tested environment (Emulator? Real Device?)

Real device

### Steps to reproduce the behavior

Using the example code from the plugin, add the google billing library in build.gradle like this:

`implementation "com.android.billingclient:billing:4.0.0"`

**Comment by hyochan** [comment]
Thanks for the issue, I'll try to upgrade the `billingClient` and migrate the code in near future.

**Comment by Gambolico** [comment]
> Thanks for the issue, I'll try to upgrade the `billingClient` and migrate the code in near future.

Thank you, have a nice day

**Comment by uzumaki258** [comment]
I think the problem caused by function name and flow is changed from v4:

```
Added Purchase#getSkus() and PurchaseHistoryRecord#getSkus(). These replace Purchase#getSku and PurchaseHistoryRecord#getSku which have been removed.
Removed BillingFlowParams#getSku, BillingFlowParams#getSkuDetails and BillingFlowParams#getSkuType.
```
I hope @hyochan can update billingClient soon.
Thank you
