### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method initConnection on channel flutter_inapp) 

### ISSUE THREAD

**Issue by bijoya-banik** [dooboolab/flutter_inapp_purchase#309]
### Version of flutter_inapp_purchase
^3.0.1

### Platforms you faced the error (IOS or An?)
android

### Tested environment (Emulator? Real Device?)
Both

Unhandled Exception: MissingPluginException(No implementation found for method initConnection on channel flutter_inapp) 
![Capture](https://user-images.githubusercontent.com/45393032/131821175-246b0456-066f-4496-8ac3-07ff56a42b70.PNG)

**Comment by godzeit** [comment]
Hello, any updates on that?

**Comment by bijoya-banik** [comment]
> Hello, any updates on that?

Yeap, I have updated the flutter version to 2

**Comment by chhsh122** [comment]
> > Hello, any updates on that?
> 
> Yeap, I have updated the flutter version to 2


> hi  which  flutter version  ?  I updated the flutter version to 2.8.1 . but I can not resolve
