### ISSUE TITLE
iOS 15 not working properly with plugin

### ISSUE THREAD

**Issue by ingokiem** [dooboolab/flutter_inapp_purchase#315]
Am I missing something or is this simply an iOS 15.0 bug and we have to wait for Apple to fix it? Anyone else having this problem?

### Version of flutter_inapp_purchase
5.0.3

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
getAvailablePurchases completes and lists the purchase history. Works on iOS 14.

### Actual behavior
getAvailablePurchases completes and lists the purchase history -but- calling it again results in getAvailablePurchases never finishing. Restarting the app does not help, rebooting the iPhone fixes it, but only for one request. I also cannot complete a purchase, the error message says "invalid product id". iOS 14 works just fine.

Looking at the Objective-C code it seems that paymentQueueRestoreCompletedTransactionsFinished is not called in the subsequent attempts.

### Tested environment (Emulator? Real Device?)
iPhone 7, iOS 15

**Comment by paperview** [comment]
getPurchaseHistory also appears to be broken in iOS 15

**Comment by offline-first** [comment]
> apple just rejected my app after reviewer test it in IOS 15. I thank him for debugging

How you solve this issue?

Apple rejected my app on iOS 15.1 iPad.
Rejection reason: We found that your in-app purchase products exhibited one or more bugs when reviewed on iPad running iOS 15.1 on Wi-Fi...

**Comment by xalikoutis** [comment]
> 

Not yet, it is very strange. I have almost 3 rejections from 3 apps, with the same message from reviewer
`We found that your in-app purchase products exhibited one or more bugs when reviewed on iPad running iOS 15.1 on Wi-Fi...`

Problem is that isnt happening in my test devices, 1 ipad and 2 iphones

**Comment by appinteractive** [comment]
any updates on that issue?

**Comment by meowofficial** [comment]
For more information the same issue on React Native:
https://github.com/dooboolab/react-native-iap/issues/1528

**Comment by meowofficial** [comment]
Future after calling `getPurchaseHistory` never resolves in production and sandbox on iOS 15.4, `flutter_inapp_purchase` 5.1.2. 
Does it work for you, guys?

**Comment by appinteractive** [comment]
Hey for me at least it was my fault by not signing the latest Tax forms. 🤷‍♂️. Another thing could be a not opened connection. Maybe that helps somehow. Since then everything started working.

**Comment by meowofficial** [comment]
@appinteractive as far as i'm concerned connection should be opened only before requesting a purchase and closed in `onPurchaseUpdated` or `onPurchaseFailed` listeners. Is it wrong?

**Comment by appinteractive** [comment]
Yes you are right. I mixed something up.

**Comment by meowofficial** [comment]
@appinteractive I tried to establish connection before purchase restoration and it worked. Thanks!

**Comment by uzumaki258** [comment]
Tesfight working fine but got rejected from Apple:
We still found that in-app purchases products exhibited one or more bugs when reviewed on iPad and iPhone running ios15.4 on Wi-Fi.
Anyone face this issue?
