### ISSUE TITLE
Unhandled Exception: PlatformException(initConnection, responseCode: 3, , null)

### ISSUE THREAD

**Issue by mix99** [dooboolab/flutter_inapp_purchase#320]
### Version of flutter_inapp_purchase
V5.0.3
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
initConnection successful
### Actual behavior
initConnection report BUG when download from google play .aab,but succeful when develop in test.
(google play use aab sign,is diffrent from test)
### Tested environment (Emulator? Real Device?)
real device
### Steps to reproduce the behavior
download from google play

**Comment by hmarat** [comment]
@mix99 did you solve this problem?

**Comment by signalmeeting** [comment]
@mix99 any updates??

**Comment by hmarat** [comment]
> @mix99 any updates??

I have problem, but I realized that it is only in emulator. For in app purchasing you have to use real device. Otherwise it will not work :)
