### ISSUE TITLE
GetProducts return nil object error

### ISSUE THREAD

**Issue by RobertBrunhage** [dooboolab/flutter_inapp_purchase#33]
### Version of flutter_inapp_purchase
0.6.5
### Platforms you faced the error (IOS or Android or both?)
IOS
### Expected behavior
Getting the products
### Actual behavior
Crashes as soon get products are called works on other devices and emulators
### Tested environment (Emulator? Real Device?)
Ipad IOS version 9.3.5
### Steps to reproduce the behavior
Calling getProducts crashes app and returns the following message:

`*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[8]'
	*** First throw call stack:
	(0x2127b91b 0x20a16e17 0x21195443 0x211952c7 0x20978a1 0x211a1625 0x2119a251 0x20970c7 0x2abb75e7 0x20de9823 0x20de980f 0x20df7ba9 0x2123db6d 0x2123c067 0x2118b229 0x2118b015 0x2277bac9 0x2585f189 0x5bd49 0x20e33873)`

**Comment by dooboolab** [comment]
@RobertBrunhage Are you saying this isn't occurring in other devices but only in your ipad ios version 9.3.5?

**Comment by RobertBrunhage** [comment]
Only have one other device that is 11.2.4 which it works on.

**Comment by dooboolab** [comment]
@RobertBrunhage It is hard to know the actual problem. Could you share any test case or codes?

**Comment by RobertBrunhage** [comment]
@dooboolab Right now I am using the example code you provide, which works great. It's only on my Ipad I get the error. The code above is the only log code I get and then the app just closes :/.

**Comment by dooboolab** [comment]
@RobertBrunhage Can you check whether initConnection return true in ios? if false, that may happen.

**Comment by RobertBrunhage** [comment]
@dooboolab Sorry for the late response. `initConnection` returns `true`.

**Comment by dooboolab** [comment]
@RobertBrunhage Could you try `0.6.8` and comeback?

**Comment by RobertBrunhage** [comment]
@dooboolab Tried it but still got the following:

`flutter: result: true
flutter: consumeAllItems: no-ops in ios
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[8]'
	*** First throw call stack:
	(0x2127b91b 0x20a16e17 0x21195443 0x211952c7 0x22f579b 0x211a1625 0x2119a251 0x22f49bd 0x2abb75e7 0x20de9823 0x20de980f 0x20df7ba9 0x2123db6d 0x2123c067 0x2118b229 0x2118b015 0x2277bac9 0x2585f189 0xd9ba9 0x20e33873)
Lost connection to device.`

**Comment by dooboolab** [comment]
@RobertBrunhage Can you share some codes? It's hard for me to debug because I can't generate this.

**Comment by RobertBrunhage** [comment]
So I call the following in initState:

`  Future<void> initPlatformState() async {
    var result = await FlutterInappPurchase.initConnection;
    print('result: $result');

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    // refresh items for android
    String msg = await FlutterInappPurchase.consumeAllItems;
    print('consumeAllItems: $msg');
    await _getProduct();
  }`

Then I have this method which is called from that:
`  Future<Null> _getProduct() async {
    List<IAPItem> items = await FlutterInappPurchase.getProducts([Constants.removeAdsProductId]);
    for (var item in items) {
      print('${item.toString()}');
      this._items.add(item);
    }

    setState(() {
      this._items = items;
    });
  }`

My render button is rather large:

`  List<Widget> _renderButton() {
    List<Widget> widgets = this._items.map((item) =>
      Column(
        children: <Widget>[
          Container(
            height: 250.0,
            width: double.infinity,
            child: Card(
              child: Column(
                children: <Widget>[
                  SizedBox(height: 28.0),
                  Align(
                    alignment: Alignment.center,
                    child: Text(language.removeAdTitle, style: Theme
                      .of(context)
                      .textTheme
                      .display1,),
                  ),
                  SizedBox(height: 24.0),
                  Align(
                    alignment: Alignment.center,
                    child: Text(language.removeAdFirstText, style: TextStyle(fontSize: 16.0, color: Colors.grey[700]),),
                  ),
                  Align(
                    alignment: Alignment.center,
                    child: Text(language.removeAdSecondText, style: TextStyle(fontSize: 16.0, color: Colors.grey[700])),
                  ),
                  SizedBox(height: 24.0),
                  SizedBox(
                    width: 340.0,
                    height: 50.0,
                    child: RaisedButton(
                      onPressed: () => _buyProduct(item),
                      shape: new RoundedRectangleBorder(
                        borderRadius: new BorderRadius.circular(30.0)),
                      child: Text('${language.buy} ${item.price} ${item.currency}', style: Theme.of(context).primaryTextTheme.button,),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      )
    ).toList();
    return widgets;
  }`

The application is crashing as soon as thsi runs, so the buy method etc is not used (not called).

(Hope this helps a bit)

**Comment by dooboolab** [comment]
@RobertBrunhage Could you try `0.6.9`? I've just checked if elements in array is not null.

**Comment by RobertBrunhage** [comment]
@dooboolab Tried it but still returns the same error.

**Comment by dooboolab** [comment]
@lukepighetti Could you help me out here (if you have time)? I am having a hard time to figure out why this is occurring.

**Comment by lukepighetti** [comment]
I don't have access to a device with that version of iOS. I'm not sure what I can do. Robert have you tried a simulator with that version?

**Comment by RobertBrunhage** [comment]
Haven't tried a simulator with that version, tried to see how I could get the version on the simulator but didn't find any info on it.

**Comment by lukepighetti** [comment]
<img width="1341" alt="screen shot 2018-09-21 at 7 28 09 pm" src="https://user-images.githubusercontent.com/666539/45910112-806acf00-bdd4-11e8-91fb-f83a822c494d.png">

**Comment by lukepighetti** [comment]
Actually, can simulators even do IAP testing? I've honestly never tried.

**Comment by dooboolab** [comment]
@lukepighetti Thanks for help. You can only test fetching product in simulator. Purchasing should be tested in real device with sandbox account.

**Comment by lukepighetti** [comment]
@RobertBrunhage if you can confirm that the problem is reproducible on Simulator I will set aside some time early this coming week to look at it.

**Comment by lukepighetti** [comment]
@dooboolab have you determined a minimum iOS version you want to support?

**Comment by dooboolab** [comment]
@lukepighetti  nope.

**Comment by lukepighetti** [comment]
To be honest I cannot find any conclusive evidence for what Apple is supporting internally. There is a mention on Wikipedia that iOS 9 is "third party support only" but I cannot find anything to support that claim.

**Comment by lukepighetti** [comment]
I did find this article. https://techcrunch.com/2018/08/23/twitter-ends-support-for-ios-9-and-lower/

**Comment by lukepighetti** [comment]
Twitter, LinkedIn, Snapchat are iOS 10+ and Facebook is iOS 9+

**Comment by lukepighetti** [comment]
https://developer.apple.com/support/app-store/ 95% of the AppStore is iOS 10+

**Comment by lukepighetti** [comment]
https://static1.squarespace.com/static/51adfbd9e4b095d664d9b869/t/5abb93381ae6cf7814528be5/1522242362088/Matrix+16by9-8k.pdf iPhone 4S and under are stuck on iOS 9

**Comment by dooboolab** [comment]
@lukepighetti Thanks for the hard research. @RobertBrunhage Maybe this symptom could be an issue from ios lacking support for an older version ios. @lukepighetti you can give this repo a `PR` to setup minimum ios version. Thank you so much!

**Comment by RobertBrunhage** [comment]
Glad we found a solution to the problem! I will implements checks for ios version before calling IAP (maybe something to add in the docs)! :)
