### ISSUE TITLE
Purchase dialog pops twice in Android in v5.1.1

### ISSUE THREAD

**Issue by xalikoutis** [dooboolab/flutter_inapp_purchase#332]
### Version of flutter_inapp_purchase
5.1.1
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
Purchase dialog should pop only once
### Actual behavior
Purchase dialog pops twice
### Tested environment (Emulator? Real Device?)
Real device
### Steps to reproduce the behavior

https://user-images.githubusercontent.com/847472/142597741-b36f4a99-2754-4a39-a4ca-90f705c8fe42.mp4

**Comment by vishhmakasana** [comment]
Hello @xalikoutis
Temporary use my forked package until my PR approved.
https://github.com/vishhmakasana/flutter_inapp_purchase
