### ISSUE TITLE
minSdkVersion upgraded

### ISSUE THREAD

**Issue by FernandoUFS** [dooboolab/flutter_inapp_purchase#338]
The minSdkVersion was upgraded, is there any specific reason for that? I have a lot of users on Android 4.4 (tablet users), but now I can't update flutter_inapp_purchase to the last version. Update notes of Android Billing SDK has no info about increasing the minSdkVersion, or I can't find it. Please, lower the minSdkVersion if there isn't any reason to upgrade. Thank you!

### Version of flutter_inapp_purchase
5.1.2

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Compile for android sdk 19.

### Actual behavior
Error on compiling, because minSdkVersion is set to 21

### Tested environment (Emulator? Real Device?)
Real Device

**Comment by FernandoUFS** [comment]
The issue still persists. I had to manually update the plugin

**Comment by deniza** [comment]
hey @FernandoUFS. This issue also bothers me now. Did you see any problems by forcing minSdkVersion 19 (or anything below 21)?

**Comment by FernandoUFS** [comment]
Hi @deniza 
I added this into my project's manifest file
```
<manifest ...
    <uses-sdk android:minSdkVersion="19" tools:overrideLibrary="com.dooboolab.flutterinapppurchase"/>
...
```

And in my pubspec I am still using:
`flutter_inapp_purchase: ^5.1.2`

Everything is ok since March

**Comment by deniza** [comment]
Thanks for the update. I was going to use a modified fork of this repo, but yours solution seems more viable.
