### ISSUE TITLE
getPurchaseHistory and refunds on Android

### ISSUE THREAD

**Issue by holyspidoo** [dooboolab/flutter_inapp_purchase#34]
When using `getPurchaseHistory()` on Android, I still see a purchase item in the list even if I issued a refund in the payment console. (Can't confirm behavior on iOS)

**Comment by marianoarga** [comment]
I'm facing the same issue, didn't find any clue in StackOverflow, the only hint I can get is related to "revoke" when you start the refund in the playstore console, but I already refund the product without checking "revoke" so it can't be tested

**Comment by marianoarga** [comment]
Tried consuming item, but got a successfull response only once, anyway the product still appears in history:

```
List<PurchasedItem> purchasedItems = await FlutterInappPurchase.getPurchaseHistory();

purchasedItems.forEach((item){
        if(item.productId == 'PRODUCT_ID'){
          FlutterInappPurchase.consumePurchase(item.purchaseToken);
        }
      });
```
