### ISSUE TITLE
Shutting down After Purchase

### ISSUE THREAD

**Issue by bringup2016** [dooboolab/flutter_inapp_purchase#343]
### Version of flutter_inapp_purchase
5.1.2
### Platforms you faced the error (IOS or Android or both?)
Android
### Tested environment (Emulator? Real Device?)
Both
### Steps to reproduce the behavior

D/AndroidRuntime(17361): Shutting down VM
E/AndroidRuntime(17361): FATAL EXCEPTION: main
E/AndroidRuntime(17361): Process: com.flutter.project, PID: 17361
E/AndroidRuntime(17361): java.lang.RuntimeException: Error receiving broadcast Intent { act=com.android.vending.billing.PURCHASES_UPDATED flg=0x10 pkg=com.flutter.project (has extras) } in com.android.billingclient.api.zzg@25d24fb
E/AndroidRuntime(17361): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1606)
E/AndroidRuntime(17361): 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
E/AndroidRuntime(17361): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(17361): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(17361): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(17361): 	at android.app.ActivityThread.main(ActivityThread.java:7615)
E/AndroidRuntime(17361): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17361): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(17361): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
E/AndroidRuntime(17361): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.dooboolab.flutterinapppurchase.MethodResultWrapper.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime(17361): 	at com.dooboolab.flutterinapppurchase.AndroidInappPurchasePlugin$7.onPurchasesUpdated(AndroidInappPurchasePlugin.java:625)
E/AndroidRuntime(17361): 	at com.android.billingclient.api.zzg.onReceive(com.android.billingclient:billing@@4.0.0:3)
E/AndroidRuntime(17361): 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1588)
E/AndroidRuntime(17361): 	... 8 more

**Comment by bringup2016** [comment]
I solved it by lowering the version to 4.0.2.

**Comment by sherpya** [comment]
I have a similar problem on crashlytics dashboard, two device, samsung Galaxy A51 (android 11)  and SPARK 6 GO (uh?) (android 10):

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void ga.j.d(java.lang.String, java.lang.Object, ga.j$d)' on a null object reference
       at com.dooboolab.flutterinapppurchase.MethodResultWrapper$4.run(MethodResultWrapper.java:11)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8595)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
as you see it's not directly by my app (somehow)

MethodResultWrapper$4.run is https://github.com/dooboolab/flutter_inapp_purchase/blob/5988a56fcec2c5dadd9e8a06097ba5df9f4bdb10/android/src/main/java/com/dooboolab/flutterinapppurchase/MethodResultWrapper.java#L56

**Comment by haorendashu** [comment]
D/AndroidRuntime(31885): Shutting down VM
E/AndroidRuntime(31885): FATAL EXCEPTION: main
E/AndroidRuntime(31885): Process: com.mizhichashao.chartmaker, PID: 31885
E/AndroidRuntime(31885): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(31885): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:286)
E/AndroidRuntime(31885): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:267)
E/AndroidRuntime(31885): 	at com.dooboolab.flutterinapppurchase.MethodResultWrapper$1.run(MethodResultWrapper.java:27)
E/AndroidRuntime(31885): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(31885): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(31885): 	at android.os.Looper.loopOnce(Looper.java:210)
E/AndroidRuntime(31885): 	at android.os.Looper.loop(Looper.java:299)
E/AndroidRuntime(31885): 	at android.app.ActivityThread.main(ActivityThread.java:8085)
E/AndroidRuntime(31885): 	at java.lang.reflect.Method.invoke(Native Method)

**Comment by umartinez22** [comment]
Are there any updates about this problem?

**Comment by 92sajid110** [comment]
yes same problem app closes after purchase

**Comment by valterh4ck3r** [comment]
Same issue here, how to fix ?

**Comment by tmaihoff** [comment]
Have a similar problem. The app crashes (closes) after successfully subscribing.
```
E/AndroidRuntime( 9037): 	at io.flutter.plugins.inapppurchase.Translator.fromPurchase(Translator.java:64)
E/AndroidRuntime( 9037): 	at io.flutter.plugins.inapppurchase.Translator.fromPurchasesList(Translator.java:97)
E/AndroidRuntime( 9037): 	at io.flutter.plugins.inapppurchase.PluginPurchaseListener.onPurchasesUpdated(PluginPurchaseListener.java:31)
```
