### ISSUE TITLE
getProducts always empty on iOS

### ISSUE THREAD

**Issue by appinteractive** [dooboolab/flutter_inapp_purchase#344]
Hi, currently my app gets rejected on iOS (android is working) as there are no products returned by `getProducts`.
When I do configure mocked ones in Xcode and run in there, it does work, but I do not get any products when running through TestFlight. Sadly, all documentation, articles, etc. on that topic are ancient. The product ID is correct, but I do not have a clue why I do not get anything back. 

Any suggestions???

### Version of flutter_inapp_purchase
5.1.2

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
`getProducts` should not be empty

### Actual behavior
`getProducts` returns always empty array (only not via Xcode with mocked configuration)

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior
- create consumable product in App Store Connect
- run app on device or publish to beta
- see no products

@hyochan @kwmt 

#315

**Comment by d9media** [comment]
Hi i was just wondering why you closed your issue - have you been able to resolve it?

Thanks

**Comment by appinteractive** [comment]
Hey yes I had a pending signature in the contracts section of appconnect regarding payment and tax stuff. Nothing was pointing in that direction, I discovered it randomly. 

Without that signature apple is not returning your products, even if they are "published" and listed as "live". I found that very unintuitive. 

Hope that helps.
