### ISSUE TITLE
Doesn't listen the status of initial payment service connection 

### ISSUE THREAD

**Issue by bijoya-banik** [dooboolab/flutter_inapp_purchase#345]
### Version of flutter_inapp_purchase
^5.0.3

### Platforms you faced the error (IOS or Android or both?)
both

### Expected behavior
initConnection function should print "connected" message

### Actual behavior
initConnection function does't listen the process of connectionUpdated

### Tested environment (Emulator? Real Device?)
both

### Steps to reproduce the behavior

 _connectionSubscription = FlutterInappPurchase.connectionUpdated.listen((connected,{error}) {
      print('connected: $connected');
    });

payment service doesn't listen to FlutterInappPurchase connection

**Comment by Vakil-Parth** [comment]
same issue
