### ISSUE TITLE
IAPItem not found - in app purchase library 

### ISSUE THREAD

**Issue by divinetechs** [dooboolab/flutter_inapp_purchase#352]
<img width="778" alt="Screenshot 2022-03-28 at 7 15 30 PM" src="https://user-images.githubusercontent.com/96619781/160411944-f5c9483c-45b1-489d-8731-62514567553a.png">

<img width="778" alt="image" src="https://user-images.githubusercontent.com/96619781/160412267-76a01200-02a7-423c-99f9-41589944e940.png">

i have added your In-App purchase library but can't use IAPItem  &  PurchasedItem model class

**Comment by deb-95** [comment]
You are depending on `in_app_purchase` which is another plugin. The correct dependency name for [this](https://pub.dev/packages/flutter_inapp_purchase) plugin is `flutter_inapp_purchase`
