### ISSUE TITLE
The Buy the same item again dialog box is not opened

### ISSUE THREAD

**Issue by luokunman** [dooboolab/flutter_inapp_purchase#354]
### Version of flutter_inapp_purchase

  flutter_inapp_purchase: ^5.1.2

### Platforms you faced the error (IOS or Android or both?)
ios Platforms

### Expected behavior
The payment dialog should pop up.

### Actual behavior
The purchase succeeds.The dialog box is not opened.

### Tested environment (Emulator? Real Device?)
Real Device. Sandbox tester

### Steps to reproduce the behavior
After a successful payment, the sandbox test account buys the same item again

**Comment by OlegNezv** [comment]
Same problem, any solution?
