### ISSUE TITLE
Add Support for macos 

### ISSUE THREAD

**Issue by alihassan143** [dooboolab/flutter_inapp_purchase#364]
Please add support for macos if you are using the storekit than it will be the same as the ios

**Comment by offline-first** [comment]
I can add support for macos if the author refactor objective c to swift :)

**Comment by alihassan143** [comment]
i don't think they have plan to refactor this code to swift

**Comment by offline-first** [comment]
@hyochan any plan to refactor to swift?

**Comment by alihassan143** [comment]
@hyochan any plan??

**Comment by alihassan143** [comment]
@hyochan any plan??
