### ISSUE TITLE
com.android.billingclient.api.ProxyBillingActivity  java.lang.NullPointerException

### ISSUE THREAD

**Issue by holyspidoo** [dooboolab/flutter_inapp_purchase#37]
I'm seeing a couple of these errors pop up in my Crashlytics. So far they only happen on Android, all on 7.1.1 (but that might be a coincidence). I'm unable to reproduce them on my devices here. 

Any ideas what it could be?

```
com.android.billingclient.api.ProxyBillingActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.IntentSender android.app.PendingIntent.getIntentSender()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
```

**Comment by holyspidoo** [comment]
I'll investigate, see what I can find. With Android, there's always this one crash you just can't reproduce on any of your devices :)

**Comment by hoanghiephui** [comment]
Need to fix, I must be this error.

**Comment by dooboolab** [comment]
Ok. I'll handle this soon.

**Comment by dooboolab** [comment]
Need help on this one because I couldn't reproduce this to debug in my env.

**Comment by hyochan** [comment]
`2.0.0+` has raised today. Please feel free to reopen after trying out `2.0.0+5` or above.
