### ISSUE TITLE
Any plan to support the new Google Play Billing Library 5.0?

### ISSUE THREAD

**Issue by KarinBerg** [dooboolab/flutter_inapp_purchase#370]
### Version of flutter_inapp_purchase
5.3.1

### Platforms you faced the error (IOS or Android or both?)
Android

### Issue description
Google released in May 2022 a new Subscription structure. see https://support.google.com/googleplay/android-developer/answer/12124625

As far as I understand (and I'm actually a beginner in Google subscriptions) this right if you use this new structure flutter_inapp_purchase will not deliver the expected results.
Example:
**Before May you created in the Play Console the following:**
- Subscription A (monthly)
    - Offer 1
- Subscription B (yearly)

**After May you create the following:**
- Subscription
    - Base plan A (monthly)
         - Offer 1
    - Base plan B (yearly)

The first base plan you create is by default the backwards-compatible base plan which is returned to the Google Play Billing Library deprecated method querySkuDetailsAsync().

See release notes of Google Play Billing Library for more info: https://developer.android.com/google/play/billing/release-notes
There is also a migration guide: https://developer.android.com/google/play/billing/migrate-gpblv5

**Comment by KarinBerg** [comment]
Any news on this?

**Comment by cruz-evan** [comment]
Any plans to update ?

**Comment by SamBergeron** [comment]
Created #392 to actually support billing 5.0, the prior PR had some issues.
