### ISSUE TITLE
android can not  initialize  

### ISSUE THREAD

**Issue by chhsh122** [dooboolab/flutter_inapp_purchase#376]
### Version of flutter_inapp_purchase
5.3.1
### Platforms you faced the error (IOS or Android or both?)
android
### Expected behavior
init success

### Actual behavior
Another exception was thrown: MissingPluginException(No implementation found for method initConnection on channel flutter_inapp)
### Tested environment (Emulator? Real Device?)
real device
### Steps to reproduce the behavior
flutter version. 2.8.1 
android version 10
     var result = await FlutterInappPurchase.instance.initialize();

problem : Another exception was thrown: MissingPluginException(No implementation found for method initConnection on channel flutter_inapp)

I can init  and example can't too

**Comment by hamza1772** [comment]
I was facing the same exact issue. 

What I did:
* Cleaned the project using #flutter clean
* Changed version to "flutter_inapp_purchase: ^5.3.0"

And it solved my problem. Try it may be it will work for you too :)

**Comment by chhsh122** [comment]
fine   it fine by itself
