### ISSUE TITLE
Method of checking if a subscription is still valid.

### ISSUE THREAD

**Issue by dshukertjr** [dooboolab/flutter_inapp_purchase#38]
I do not see a method of checking is a subscription is still valid in both iOS and Android. PurchacedItem should have property for that, I think.

**Comment by dooboolab** [comment]
@dshukertjr Do you know how to do this process in native side? If you do, the only way to do is by validating receipt with rest APIs supported from each platform(`ios` and `android`). I've yet supported checking receipt in this module. I'll make some `rest api call method` in near future but won't have `checking subscription` kind of method in futrue either.

**Comment by dooboolab** [comment]
I will close this since `validateReceiptIos` and `validateReceiptAndroid` have been included in `0.7.1`.
