### ISSUE TITLE
Use Amazon SDK remote binary instead of local binary *.jar

### ISSUE THREAD

**Issue by dtvtkien** [dooboolab/flutter_inapp_purchase#380]
### Set of dependencies:
```
dependencies:
  flutter:
    sdk: flutter
  flutter_inapp_purchase: ^5.3.1
  purchases_flutter: ^4.0.0
```

### Detail about the issue:
- 2 both library depend on Amazon In-app-purchase SDK: 
  - `purchases_flutter` is using version 3.0.3, which is now distributed in Maven. 
  - `flutter_inapp_purchase` is depending on local binary `in-app-purchasing-2.0.76.jar`

- When I run command `flutter run`, I received the following error logs:
  - Duplicate class com.amazon.device.iap.model.UserDataResponse found in modules jetified-amazon-appstore-sdk-3.0.2 (com.amazon.device:amazon-appstore-sdk:3.0.2) and jetified-in-app-purchasing-2.0.76 (in-app-purchasing-2.0.76.jar)
  - Duplicate class com.amazon.device.iap.model.UserDataResponse$RequestStatus found in modules jetified-amazon-appstore-sdk-3.0.2 (com.amazon.device:amazon-appstore-sdk:3.0.2) and jetified-in-app-purchasing-2.0.76 (in-app-purchasing-2.0.76.jar)...

- For more information, please refer to this [link](https://github.com/RevenueCat/purchases-flutter/issues/417#issuecomment-1209190697)

Could you update the Amazon SDK dependency to the newest version which was distributed in Maven?

**Comment by rwrz** [comment]
@dtvtkien feel free to use this PR I just sent. But keep in mind, it is NOT fully tested, but you will be able to compile and run your app again.
