### ISSUE TITLE
Not getting Subscription List

### ISSUE THREAD

**Issue by MdFarhanRaja** [dooboolab/flutter_inapp_purchase#381]
### Real Device
<img width="1669" alt="Screenshot 2022-08-10 at 2 38 27 PM" src="https://user-images.githubusercontent.com/18304656/183863010-81280ad0-00f9-4bd7-a05b-5b7ac7090c1e.png">
<img width="1300" alt="Screenshot 2022-08-10 at 2 39 38 PM" src="https://user-images.githubusercontent.com/18304656/183863027-390d1b08-537b-4645-b245-b13613855a15.png">

**Comment by MdFarhanRaja** [comment]
only getting first item #3_month_subcription_test

**Comment by yunchiri** [comment]
have you solved?

**Comment by MdFarhanRaja** [comment]
> have you solved?

No

**Comment by MdFarhanRaja** [comment]
> have you solved?

How to solve this ?

**Comment by yunchiri** [comment]
No , I'm same situation like you 🤣

**Comment by AnhLT-Nexle** [comment]
It might not help you guys but I faced a problem similar. I cannot get products if I pass only productID, I must pass productName also(or any string that I do not test) then I can get the products

**Comment by yunchiri** [comment]
> It might not help you guys but I faced a problem similar. I cannot get products if I pass only productID, I must pass productName also(or any string that I do not test) then I can get the products

how to pass productName ?

could you show me example code?

**Comment by AnhLT-Nexle** [comment]
I created the product with productName: Monthly Consumable and productID: consumable_monthly.
final  _productIds = ["consumable_monthly",  "Monthly Consumable"]
final products = await FlutterInappPurchase.instance.getProducts(_productIds)
Somehow if I set _productIds contains only productID then I cannot get any item from FlutterInappPurchase.instance.getProducts

**Comment by AnhLT-Nexle** [comment]
> > It might not help you guys but I faced a problem similar. I cannot get products if I pass only productID, I must pass productName also(or any string that I do not test) then I can get the products
> 
> how to pass productName ?
> 
> could you show me example code?

I created the product in play console with name: Monthly Consumable and productID: monthly_consumable
final products = await FlutterInappPurchase.instance.getProducts(["monthly_consumable", "Monthly Consumable"]);
If I use FlutterInappPurchase.instance.getProducts with param is only productID then it returns list empty but with the params above it worked

**Comment by RodolfoSilva** [comment]
@MdFarhanRaja, @yunchiri  I was having the same problem as you, it turns out we were using the wrong method to get signatures. I used `getSubscriptions` and it works fine.

I believe the `getProducts` method is made available only for consumable, not for subscriptions product.
