### ISSUE TITLE
PlatformException(getSubscriptions, E_NOT_PREPARED, IAP not prepared. Check if Google Play service is available., null)

### ISSUE THREAD

**Issue by goddev999** [dooboolab/flutter_inapp_purchase#390]
When trying to run the getSubscriptions, I got this error
  final List<String> _productIds = [
    'plus_sub',
    'plus_diamond',
    'plus_subscription_android',
    'diamond_subscription_android',
  ];
FlutterInappPurchase.instance.getSubscriptions(_productIds);

How to fix this error?

**Comment by radheyshyamideastoimpacts** [comment]
Before using make sure you initialized like:     await FlutterInappPurchase.instance.initialize();

**Comment by goddev999** [comment]
Thank you for your reply.
I tried to run the initialization.
I got an error like this.
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(initConnection, responseCode: 3, , null)

**Comment by robertocsd** [comment]
anyone found a solution for this?
