### ISSUE TITLE
Implementation of paymentQueue:shouldAddStorePayment

### ISSUE THREAD

**Issue by Zil85** [dooboolab/flutter_inapp_purchase#41]
I have added (paymentQueue:shouldAddStorePayment) for handling IAP's initiated directly on the App Store for iOS (https://developer.apple.com/documentation/storekit/skpaymenttransactionobserver/2877502-paymentqueue?language=objc)

This function is called on app start. But since it might not be convenient to start a purchase at that point, I have implemented it in a way that it stores any products that the user has attempted to buy on the App Store in an array.

The products can then be fetched using the new dart function "getAppStoreInitiatedProducts()" whenever the developer wants to handle the product, and then use the standard flow for starting the purchase.

For Android it always just returns an empty array.

It's been tested on a real device iPhone SE running iOS 12. But have not tested on older device, pre iOS 11.0. As this is when the function was introduced.

Have also corrected "buyProductWithoutFinishTransaction" for iOS, it was not sending the productId.
And some issues with the "toString" function for the "IAPItem".

I'm quite new to this whole setup, can I just submit a PR, or do you want to see if this is at all in line with how you see the plugin progressing?

**Comment by dooboolab** [comment]
@Zil85 It is hard to understand your situation without any codes. If you give us a `PR` it would be more helpful.

**Comment by Zil85** [comment]
Ok, Done.

**Comment by dooboolab** [comment]
@Zil85 Thank you for the PR. Could you also write some `Readme` and `Changelog.md` about this update? I may take time to understand this.

**Comment by Zil85** [comment]
I have done that now.
Please let me know if there is more I need to fill in.
This is my first PR. :)
