### ISSUE TITLE
New Version of IPhone App Rejected

### ISSUE THREAD

**Issue by Rockvole** [dooboolab/flutter_inapp_purchase#45]
![reject](https://user-images.githubusercontent.com/4139576/47260623-d2eee800-d473-11e8-92b9-47707c4ecf29.png)

[In-App Purchase Programming Guide](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Introduction.html)

Which method would I call in a "restore" button ?

**Comment by Rockvole** [comment]
This issue has a similar type of discussion :
https://github.com/dooboolab/react-native-iap/issues/90

Although I have no consumables, it is just a single purchase for each install.
Using V0.7.0

**Comment by Rockvole** [comment]
This also has a similar discussion.
https://github.com/dooboolab/react-native-iap/issues/3

**Comment by dooboolab** [comment]
As descried in dooboolab/react-native-iap#90, you should have restore button inside your app to solve this restriction. The Apple reviewer is not a developer, they are just normal user who follow Apple's ux guideline.

**Comment by dooboolab** [comment]
As descried in dooboolab/react-native-iap#90, you should have restore button inside your app to solve this restriction if it isn't a `consumable`. The Apple reviewer is not a developer, they are just normal user who follow Apple's ux guideline.

**Comment by dooboolab** [comment]
As descried in dooboolab/react-native-iap#90, you should have restore button inside your app to solve this restriction if it isn't a consumable. The Apple reviewer is not a developer, they are just normal user who follow Apple's ux guideline.
