### ISSUE TITLE
Crashes on iOS10.3

### ISSUE THREAD

**Issue by robisaks** [dooboolab/flutter_inapp_purchase#46]
### Version of flutter_inapp_purchase
0.8.3
### Platforms you faced the error (IOS or Android or both?)
iOS (10.3), works on iOS 12
### Tested environment (Emulator? Real Device?)
Real device and emulator
### Steps to reproduce the behavior
Add package to project, call
`FlutterInappPurchase.checkSubscribed(sku:"adfree")`
`FlutterInappPurchase.getSubscriptions(['adfree'])`

**Error (pretty)**:
https://gist.github.com/robisaks/478c2bec2145d6e9be097bdb306791ff
**Error (raw)**:
`
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[8]'
*** First throw call stack:
(
        0   CoreFoundation                      0x000000010873db0b __exceptionPreprocess + 171
        1   libobjc.A.dylib                     0x00000001081a2141 objc_exception_throw + 48
        2   CoreFoundation                      0x0000000108658a62 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 354
        3   CoreFoundation                      0x00000001086588cb +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
        4   flutter_inapp_purchase              0x00000001050184bf -[FlutterInappPurchasePlugingetProductAsDictionary:] + 3919
        5   flutter_inapp_purchase              0x000000010501744e __65-[FlutterInappPurchasePlugin productsRequest:didReceiveResponse:]_block_invoke + 110
        6   CoreFoundation                      0x00000001087961ba -[__NSSingleObjectArrayI enumerateObjectsWithOptions:usingBlock:] + 58
        7   flutter_inapp_purchase              0x0000000105017316 -[FlutterInappPurchasePluginproductsRequest:didReceiveResponse:] + 486
        8   StoreKit                            0x0000000104fcd9db __34-[SKProductsRequest _handleReply:]_block_invoke + 469
        9   libdispatch.dylib                   0x000000010aea8585 _dispatch_call_block_and_release + 12
        10  libdispatch.dylib                   0x000000010aec9792 _dispatch_client_callout + 8
        11  libdispatch.dylib                   0x000000010aeb1247 _dispatch_main_queue_callback_4CF + 1041
        12  CoreFoundation                      0x0000000108702909 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
        13  CoreFoundation                      0x00000001086c8ae4 __CFRunLoopRun + 2164
        14  CoreFoundation                      0x00000001086c8016 CFRunLoopRunSpecific + 406
        15  GraphicsServices                    0x000000010c67ea24 GSEventRunModal + 62
        16  UIKit                               0x0000000108b61134 UIApplicationMain + 159
        17  Runner                              0x0000000101d9f047 main + 55
        18  libdyld.dylib                       0x000000010af1265d start + 1
)
`

**Comment by dooboolab** [comment]
I'll close this please repen if it still occurs.

**Comment by robisaks** [comment]
Thanks! Yes, 0.8.4 resolve the issue.
