### ISSUE TITLE
getProducts returns empty list when query with multiple ids

### ISSUE THREAD

**Issue by mrmikezhang** [dooboolab/flutter_inapp_purchase#48]
### Version of flutter_inapp_purchase 
0.8.5

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
Get all products

### Actual behavior
Empty array, when using multiple ids

### Tested environment (Emulator? Real Device?)
Real device

### Steps to reproduce the behavior
call FlutterInappPurchase.getProducts() with multiple ids

For some reason it works fine when I only use one product id, but if I use an array of ids then it will give me an empty arrary.
var items = await FlutterInappPurchase.getProducts(["product.id1"]) works fine
var items = await FlutterInappPurchase.getProducts(["product.id2"]) works fine
var items = await FlutterInappPurchase.getProducts(["product.id1","product.id2"]) empty array

PS. probably not the right place for this, but I really want to say thank you for this awesome package. :)

**Comment by dooboolab** [comment]
This should work because I've already tested this in example project with array. It is hard to figure out until what actually you've done wrong.

**Comment by mrmikezhang** [comment]
Hi thanks for getting back to me. So I tried to run the same code on the same device again this morning, and guess what it worked. I don't know exactly what's going on, but I guess it could have something to do with Google. Seems like you have to wait a few hours before you can do queries with multiple product ids. Weird...

Anyways, thanks again, I will see myself out and have a great day.
