### ISSUE TITLE
getSubscriptions

### ISSUE THREAD

**Issue by RobertBrunhage** [dooboolab/flutter_inapp_purchase#5]
I have followed the readme but can't figure out how to fetch subscriptions because the method returns PurchasedItem instead of list<IAPItem> as the normal getProducts does.

In the documentation, it says that getSubscription should return a list of items.

**Comment by dooboolab** [comment]
@RobertBrunhage Sorry. That was a miss. I'll update now.

**Comment by dooboolab** [comment]
@RobertBrunhage Updated in `0.4.3`. Please reopen when you still face the issue.
