### ISSUE TITLE
Pro Guard rules?

### ISSUE THREAD

**Issue by edgartrem** [dooboolab/flutter_inapp_purchase#50]
### Version of flutter_inapp_purchase

0.8.7

### Platforms you faced the error (IOS or Android or both?)

Android

### Expected behavior

Build Realease APK

### Actual behavior

Fails

### Steps to reproduce the behavior

Run `flutter build apk`

I could't get a release build until I added the following in my `pro-guardrules.pro`

`-keep class com.dooboolab.** { *; }`
`-keep class com.android.vending.billing.**`
`-dontwarn com.amazon.**`
`-keep class com.amazon.** {*;}`
`-keepattributes *Annotation*`

Maybe add something in README?

**Comment by dooboolab** [comment]
Merged your `PR`. Thanks.
