### ISSUE TITLE
flutter IAP how to “Restore Purchases”

### ISSUE THREAD

**Issue by z2228391** [dooboolab/flutter_inapp_purchase#52]
### Version of flutter_inapp_purchase
Flutter 1.0.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (2 weeks ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

### Platforms you faced the error (IOS or Android or both?)
Both

### Tested environment (Emulator? Real Device?)
Real Device

### Steps to reproduce the behavior

I am using flutter_inapp_purchase for my flutter app's IAP of non-Consumable product. For IOS, it does need to include a "Restore Purchases" feature to allow users to restore the previously purchased in-app purchases. May I know how to create "Restore" button and initiate the restore process when the "Restore" button is tapped by the user?

https://stackoverflow.com/questions/53776179/flutter-iap-how-to-restore-purchases

**Comment by hyochan** [comment]
@z2228391 You can put restore button anywhere you want based on my knowledge (correct me if I am wrong). You can then use `getAvailablePurchases` to proceed this.

**Comment by hyochan** [comment]
Since I feel this isn't a issue, I will close this for now.

**Comment by ozexpert** [comment]
@hyochan i was referring non-consumable products as well.
