### ISSUE TITLE
FlutterInappPurchase.buyProduct(skuId) errored even though purchase was successful

### ISSUE THREAD

**Issue by mrmikezhang** [dooboolab/flutter_inapp_purchase#54]
### Version of flutter_inapp_purchase
flutter_inapp_purchase: ^0.8.5

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
Purchase non-consumable without error using FlutterInappPurchase.buyProduct(skuId)

### Actual behavior
The product is successfully purchased, but Apple somehow throw an PlatformException, and ask the user to re-enter their password. Sometimes, the user needs to press the buy button again and Apple will ask the user to restore the purchase because they already own it. I am wondering if I should use FlutterInappPurchase.buyProductWithoutFinishTransaction instead or if that's going to make any difference.

### Tested environment (Emulator? Real Device?)
real device

### Steps to reproduce the behavior
Happens intermittently

Hope you can shed a light on this, I am read all the docs, couldn't seem to find a solution around it.
Thank you.

**Comment by hyochan** [comment]
@mrmikezhang Yes. This is generally unexpected use-case generated by `Apple`. I've made a workaround for `react-native-iap` in [PR](https://github.com/dooboolab/react-native-iap/issues/307) and not yet for this one. I wish I can get back here to support this in this plugin too.

**Comment by mrmikezhang** [comment]
@hyochan Thanks for getting back to me. It's good to know that I am not causing the problem. Right now I am using buyProductWithoutFinishTransaction to see if that will help mitigate the problem.

**Comment by hyochan** [comment]
@mrmikezhang Hi there. I am trying to manage this problem in this plugin also. See #58.

**Comment by hyochan** [comment]
Closing this for now. Please reopen when this isn't working as expected.
