### ISSUE TITLE
How to cancel a subscription on Android?

### ISSUE THREAD

**Issue by StaymanHou** [dooboolab/flutter_inapp_purchase#57]
We'd like to place a button by which user can cancel their current subscription on Android.

I've went through the API reference but could find a single word mentioning that.

The only way I've found so far is invoking the `buySubscription` method with the `productId` of the current subscription `PurchasedItem`. That shows the following `BottomSheet`. And users have to click the `manage subscriptions` to cancel it, which is not a very good UX.

![photo_2019-01-24_10-59-19](https://user-images.githubusercontent.com/5069041/51690895-b066f080-1fc7-11e9-911a-1f0ae2d8278d.jpg)

Is there a better way to implement it?

**Comment by hyochan** [comment]
@StaymanHou Currently not supported in our plugin(Users should cancel themselves). Hope you to ask these kinds of questions through `stackoverflow` and guide us because we've not found any cancellation directly in each platform when implementing this.

**Comment by StaymanHou** [comment]
@hyochan Thanks for the prompt reply. After some research, it appears that I would have to do it either from backend using Google Play API or through a deeplink that opens the subscription management in the Play Store app.

**Comment by StaymanHou** [comment]
I ended up implementing a method `Future launchSubscriptionManagement(String sku, {String androidAppId})` to launch the play store subscription management activity. I can make a PR if you think it's good to include in this plugin.

**Comment by hyochan** [comment]
@StaymanHou It would be nice if you can share your work.
