### ISSUE TITLE
Error building apk release

### ISSUE THREAD

**Issue by juanjoserodrigolazaro** [dooboolab/flutter_inapp_purchase#59]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.13.6 17G3025, locale es-CL)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.3.1)
[✓] Connected device (1 available)

• No issues found!

When i compile it gives me this error:

Compiler message:
file:///Users/imac/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inapp_purchase-0.8.8+1/lib/flutter_inapp_purchase.dart:89:39: Error: Expected 0 type arguments.
      dynamic result = await _channel.invokeMethod<dynamic>(
                                      ^

**Comment by hyochan** [comment]
@juanjoserodrigolazaro 
```
➜  example git:(master) ✗ flutter build apk --release   
Initializing gradle...                                              2.6s
Resolving dependencies...                                           3.6s
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       9.4s
Built build/app/outputs/apk/release/app-release.apk (5.1MB).
```

I've just tried in `example` dir and works fine. Need more useful things to dig in.
