### ISSUE TITLE
Date Subscription Renew

### ISSUE THREAD

**Issue by RobertBrunhage** [dooboolab/flutter_inapp_purchase#6]
Is there any way to get the date the subscription will renew after you bought it? I can see a TransactionDate but not when it will renew.

Would like to see a PurchasedItem.renewDate or something similar.

Or is it something I am missing?

**Comment by dooboolab** [comment]
@RobertBrunhage Um.. Currently, I've no idea how to get it. I'll look for this one. Also I found this in [stackoverflow](https://stackoverflow.com/questions/18924411/how-to-get-ios-appstorereceipturl-into-base-64-encoded-string/18927587#18927587).

**Comment by RobertBrunhage** [comment]
I know that the FlutterPayments pub has a renewDate variable, will try to see if I can understand it there and comment back here if I found anything!

**Comment by RobertBrunhage** [comment]
Here he created the variable purchaseExpires variable: https://github.com/delightfulgoods/flutter_payments/blob/master/lib/src/purchase.dart

**Comment by dooboolab** [comment]
@RobertBrunhage Oh. Yes that is supported from `ios 11.0.2`. I can manage this in `ios` using this [one](https://github.com/dooboolab/react-native-iap/blob/8e40f497ac1f36c9ab42f853f7d437673ee6db74/ios/RNIapIos.m#L286). I may take some time cause I am working on something else now. I'll try this on the weekend.

**Comment by RobertBrunhage** [comment]
If it helps it seems he gets this:

![image](https://user-images.githubusercontent.com/26344867/43855521-2ca24016-9b46-11e8-9885-d5023bd4889c.png)

And then have this function that he adds it on

![image](https://user-images.githubusercontent.com/26344867/43855543-3d97f230-9b46-11e8-800b-3247525e6b5b.png)

Thanks mate, looking forward to it! Will you look into android also? Testing it out on android atm :)

**Comment by dooboolab** [comment]
@RobertBrunhage Yes I've seen it. I may get `subscriptionPeriod` parameter but I won't transcode it like he did. That may be done manually with `developer`.

**Comment by RobertBrunhage** [comment]
Yeah that would be great also, I just need a way to get the period of the subscription.

**Comment by dooboolab** [comment]
@RobertBrunhage I've just implemented the call for `subscriptionPeriod`. I've read through the docs and found that `android` and `ios` are giving different types of variables for this. I may manage to be the same later but currently, I've just bridged the parameter that is sent from each platform. Also, `flutter_payments` plugin only had `subscriptionPeriod` sent from `android` when I looked in the code. Just remind yourself.

Here is general guide for getting the period for each platform.
* Android - `subscriptionPeriodAndroid` will give you a period in milisecs.
* IOS - `subscriptionPeriodNumberIOS` will give you the unit number and `subscriptionPeriodUnitIOS` will give you the unit in `String` like `DAY` or `WEEK` or `MONTH` or `YEAR`.

**Comment by RobertBrunhage** [comment]
Awesome! Just another question, how do you check if a subscription is active?

**Comment by RobertBrunhage** [comment]
Also tried `print(items[0].subscriptionPeriodAndroid);` which returns `P1W.`

**Comment by dooboolab** [comment]
@RobertBrunhage You can refer [here](https://github.com/dooboolab/react-native-iap/issues/202) but I think only way is to check the receipt.

**Comment by dooboolab** [comment]
@RobertBrunhage Oops what's that? Let me check.

**Comment by dooboolab** [comment]
@RobertBrunhage Sorry I was wrong. Maybe I read the wrong article. [Here](https://developer.android.com/google/play/billing/billing_reference) you may know what `P1W` stands for.

**Comment by RobertBrunhage** [comment]
Ahh okay, thanks! 

Still having problems understanding how to check if a subscription is active though. I store the date on my server on when the subscription will end so that I only check the IAP when that date is reached. Then I want to check again if it is renewed or not to add the new date.

**Comment by dooboolab** [comment]
@RobertBrunhage I think you should check that with rest apis in each platform. Currently, you may follow [here](https://developers.google.com/android-publisher/api-ref/purchases/subscriptions/get) for android. And follow [here](https://stackoverflow.com/questions/18161036/how-to-detect-and-verify-a-renewal-for-an-auto-renewable-subscription) for ios.

**Comment by dooboolab** [comment]
Closing this for now since this is no more an issue.

**Comment by lukepighetti** [comment]
@RobertBrunhage There seems to be no native way to check subscription status, but I do have this working in theory which might be useful to you. I may do a PR to add this as a convenience method.

This assumes there is only one product and it is a subscription.

```dart
  getHistory() async {
    await FlutterInappPurchase.prepare;

    if (Platform.isIOS) {
      var history = await FlutterInappPurchase.getPurchaseHistory();
      FlutterInappPurchase.endConnection;

      history.sort((a, b) => (a.transactionDate.millisecondsSinceEpoch)
          .compareTo(b.transactionDate.millisecondsSinceEpoch));

      final transactionDate = history.last.transactionDate;
      int minutes = DateTime.now().difference(transactionDate).inMinutes;
      bool isSubscribed = minutes <= 5;

      print(
        'we ${isSubscribed? "are" : "are not"} subscribed, sub is ${minutes}m old',
      );

      return isSubscribed;
    } else if (Platform.isAndroid) {
      var history = await FlutterInappPurchase.getPurchaseHistory();
      var purchases = await FlutterInappPurchase.getAvailablePurchases();
      FlutterInappPurchase.endConnection;

      for (var purchase in purchases) {
        if (purchase.productId == "when_coin_premium") {
          print('subscribed!');
          return true;
        }
      }
      print('not subscribed');
      return false;
    }
  }
```

**Comment by RobertBrunhage** [comment]
@lukepighetti Yeah, I would love to see that as a convenience method!

**Comment by dooboolab** [comment]
@lukepighetti Review this [commit](https://github.com/dooboolab/flutter_inapp_purchase/commit/860be6631ce3555803b1d4a947534faf00ac7db0). I've made changes to your method.

**Comment by lukepighetti** [comment]
That's fine with me! :)

**Comment by JayM96** [comment]
@lukepighetti  @hyochan @RobertBrunhage Did you found any way to check that any subscription is active at the time or not? If it is cancelled from play store even then we can have that response properly.

Can you suggest me how can i achieve this subscription date expiry or active subscription ?

This is most important feature reuired for subscription part. But, still there is not so much solutions available. Can we have any workaround solutions for this?

Thanks.

**Comment by RobertBrunhage** [comment]
> @lukepighetti @hyochan @RobertBrunhage Did you found any way to check that any subscription is active at the time or not? If it is cancelled from play store even then we can have that response properly.
> 
> Can you suggest me how can i achieve this subscription date expiry or active subscription ?
> 
> This is most important feature reuired for subscription part. But, still there is not so much solutions available. Can we have any workaround solutions for this?
> 
> Thanks.

I went with RevenueCat for subscriptions instead, worked wonders :)
