### ISSUE TITLE
getAvailablePurchases returns nothing on IOS when no internet connection

### ISSUE THREAD

**Issue by sercanersoy** [dooboolab/flutter_inapp_purchase#60]
### Version of flutter_inapp_purchase
0.8.8+1
### Platforms you faced the error (IOS or Android or both?)
Only IOS
### Expected behavior
Returning purchases made previously
### Actual behavior
Does not return anything
### Tested environment (Emulator? Real Device?)
Real device
### Steps to reproduce the behavior
Cut your internet connection and try calling 'await getAvailablePurchases()' or similarly 'await getPurchaseHistory()'

First of all, I appreciate your work. Plug-in works just perfect in Android. It is very easy to use.

Problem is that, when user is not connected to internet, functions 'getAvailablePurchases' or 'getPurchaseHistory' does not return anything. Because they return nothing and used with await, instructions after these functions are not executed. When connected to internet, everything works just fine. With or without connection, these functions works just fine on Android by the way.

I will be appreciated if you can solve this. My app needs to run offline properly, for that I need to use these functions. Hope you can help, thanks by now

**Comment by hyochan** [comment]
@sercan-ersoy-2015400039 Yea. Our latest version (0.8.8+1) currently corrupted. I am fixing it right now. Please use `0.8.8` for now until this is fixed.

**Comment by hyochan** [comment]
Well sorry, I've just carefully read yours but what you've written seems unrelated to what I am doing.

**Comment by ozexpert** [comment]
this happens on Android too.

**Comment by sercan-ersoy-2015400039** [comment]
@ozexpert My Android app works fine when no connection. Checked again when I read you, it's still working 👍🏼

**Comment by sercan-ersoy-2015400039** [comment]
@hyochan Are you also facing this issue? Asking to detect if I am doing something wrong.

**Comment by hyochan** [comment]
@sercan-ersoy-2015400039 Actually, I am not using this in any of our apps. I've just ported `react-native-iap` here.

**Comment by ozexpert** [comment]
@sercan-ersoy-2015400039 @hyochan  donno what the differences are, but my android app returns empty list for non-consumable products (i have no consumable products).

**Comment by sercan-ersoy-2015400039** [comment]
@ozexpert @hyochan By returns nothing I mean literally nothing. Not empty list, not null. So, "await getAvailablePurchases()" executes forever, instructions called after this are not executed at all because it does not terminate. Of course there are difference between what you are saying and what I am facing. And I am facing this situation only on IOS when there is no internet connection.

**Comment by hyochan** [comment]
`2.0.0+` has raised today. Please feel free to reopen after trying out `2.0.0+5` or above.
