### ISSUE TITLE
Non-consumable products seems not returned when getAvailablePurchases() is called

### ISSUE THREAD

**Issue by ozexpert** [dooboolab/flutter_inapp_purchase#61]
### Version of flutter_inapp_purchase
0.8.8

### Platforms you faced the error (IOS or Android or both?)
Android (i have not yet tested on iOS)

### Expected behavior
*Non-consumable* products are not returned when calling getAvailablePurchases() API. 

### Actual behavior
Non-consumable products should be returned.

### Tested environment (Emulator? Real Device?)
Real Device - Samsung Galaxy Note 8

### Steps to reproduce the behavior
```
await FlutterInappPurchase.initConnection;

List<PurchasedItem> purchasedItems = await FlutterInappPurchase.getAvailablePurchases();
print('purchased items: $purchasedItems');

await FlutterInappPurchase.endConnection;
```
above code prints 
`purchased items: []`

**Comment by hyochan** [comment]
I am sorry but currently, my environment is not sufficient to test these. I'll leave this up here for someone to join the problem.

**Comment by xuguoyii** [comment]
Me too. ids are okay, but the list is empty.

**Comment by ArtfulDodgerB92** [comment]
I am having issues with it returning nothing as well, I have tried even rebuilding my store from scratch.   Plugin never finds my product, but will return the android.test.purchased ones just fine.

**Comment by hyochan** [comment]
`2.0.0+` has raised today. Please feel free to reopen after trying out `2.0.0+5` or above.
