### ISSUE TITLE
Getting "platform not supported" on iOS devices

### ISSUE THREAD

**Issue by mrmikezhang** [dooboolab/flutter_inapp_purchase#64]
### Version of flutter_inapp_purchase
^0.8.8+2

### Platforms you faced the error (IOS or Android or both?)
IOS

### Expected behavior
Successful purchase

### Actual behavior
getting platform not supported exception

### Tested environment (Emulator? Real Device?)
real device

### Steps to reproduce the behavior
NA

Hi there, one of my customers is getting "platform not supported" exception when trying to purchase one of my non consumable products. 

Below is the device details that was captured
`{
    name: "removed for privacy"
    model: "iPhone10,6"
    systemName: "iOS"
    systemVersion: "12.1.4"
    isPhysicalDevice: true
}`

I looked it up and found that it's caused by the `static Future<PurchasedItem> buyProduct(String sku) async` function. The exception was thrown at package:flutter_inapp_purchase/flutter_inapp_purchase.dart:242, because it somehow failed to detect the user's platform correctly.

This is the first time I am getting this error, what's weird is that the user's platform was successfully detected in my code, but for some reason, it failed to do so in the flutter_inapp_purchase.dart class (https://github.com/dooboolab/flutter_inapp_purchase/blob/master/lib/flutter_inapp_purchase.dart), even though it's using the same Platform.isIOS method, which worked fine in my code, since I am able to get the device info and mapped to the deviceDetails object shown above.

This could be a glitch, but I am just curious if anyone else has experienced this before, many thanks.

**Comment by mrmikezhang** [comment]
just got this exact same error again on another iOS device from our user today.

**Comment by mrmikezhang** [comment]
Ok, I have done some extensive debugging, and found out that it's not really related to the platform nor failed purchase.

Basically, every time the user cancels the purchase, this error will show up. In the previous versions I could get the correct error code/message ie. "The purchase was canceled", but it seems not to work for the new version (^0.8.8+2). I tested it on a live android device as well, and the error code is correct. It's only affecting the iOS devices. hope it'd help you narrow down the problem.

Many thanks.

**Comment by JeffScaturro** [comment]
@mrmikezhang Hello!

I was just running into this issue as well. I'm not sure why it behaves this way, or why it fixes it, but this is what fixed it for me:

I had to make sure I got all the products available before doing anything. Once I changed my `asnycInitState` to include my `getIAPS()` I was able to popup the prompt to purchase the product. I suspect there are things that need to make sure the products are available.

In my case, throwing a breakpoint deep down in `[buyProduct](https://github.com/dooboolab/flutter_inapp_purchase/blob/master/lib/flutter_inapp_purchase.dart#L248)` got me the information that there wasn't a product available with the productID I was providing (though there is).

For what it's worth, the platform is being correctly identified. The wrong exception is just being thrown.

```.dart
void asyncInitState() async {
    await FlutterInappPurchase.initConnection.then((message) {
      print('FlutterInappPurchase.initConnection: $message');
    });
    await getIAPs();
    await restorePurchases();
   ...
}
```

```.dart
Future getIAPs() async {
    List<IAPItem> iaps = await FlutterInappPurchase.getProducts(iapList);

    _availableIAPsController.sink.add(iaps);
}
```

Hope that helps some!

(fyi @hyochan)

**Comment by mrmikezhang** [comment]
@JeffScaturro Hi there,

Thanks for sharing that information with me. I will give it a go tonight and see if it works in my case. I will get back to you once I have tested it. 

Cheers

**Comment by mrmikezhang** [comment]
@JeffScaturro I just double checked my code, and realized that I was doing the exact the same thing as you already, however the error is still there. What happens if you cancel the purchase on an IOS device now? Do you get the "Platform not supported" error?

**Comment by JeffScaturro** [comment]
@mrmikezhang Yes, if I cancel the purchase the error thrown  is a platform not supported exception:
`PlatformException (PlatformException(ios, platform not supported, null))` from cancelling the dialog prompted by `await FlutterInappPurchase.buyProduct(sku).then((purchasedItem)...`.

**Comment by mrmikezhang** [comment]
@JeffScaturro ye, something is probably broken, because it used to work fine. I used to be able to get "The purchase was cancelled by the user" error instead.

**Comment by ext452** [comment]
@JeffScaturro, @mrmikezhang  hi !
Look at the `flutter_inapp_purchase.dart`, all platform exception is `throw PlatformException(
        code: _platform.operatingSystem, message: "platform not supported");`
There no "The purchase was cancelled by the user" message in exceptions or any other
Sorry for my english ;)

**Comment by JeffScaturro** [comment]
@ext452 In that file, that exception is thrown if it reaches the end of that method. There are two branches there, one for Android, and the other for iOS. If the method continues to execute, we are throwing the `PlatformException` because we didn't go into either of the branches, and thus are expecting that the platform is not supported.

If you take a look in [FlutterInappPurchasePlugin.m](https://github.com/dooboolab/flutter_inapp_purchase/blob/master/ios/Classes/FlutterInappPurchasePlugin.m#L430) you can see that there are more specific error codes, and their respective description in the next method.

@kwmt might this be related to work done in a183bfd71c72581394a2fe1d827fd6836223fdd9?

**Comment by wu0792** [comment]
@mrmikezhang 
I just came cross the exception and solved it by calling

`await FlutterInappPurchase.initConnection;` before calling buyProduct

the ReadMe.md expalins the initConnection field as following:

> Prepare IAP module. Must be called on Android before any other purchase flow methods. In ios, it will simply call canMakePayments method and return value.

**Comment by mrmikezhang** [comment]
@wu0792 
Hi there, thanks for letting me know. However I don't think that's the cause of the issue. As I said earlier, it only occurs on iOS and I did call the initConnection method before attempting to make a purchase. Many of my users don't have problem purchasing the app, the incorrect error message only gets triggered when a user cancels the purchase. Instead of showing "Purchase cancelled by user" like it did before, it now shows "platform not supported".

**Comment by alexandergottlieb** [comment]
The problem is the iOS catch block doesn't end in a return statement. So, when the user cancels and generates an `E_USER_CANCELLED` exception, control is passed back to outside the if/else and the "platform not supported" exception is thrown.

I've added some comments to the `buyProduct` function to show what I mean:

```
} else if (_platform.isIOS) {
      try {
        dynamic result = await _channel.invokeMethod(
            'buyProductWithFinishTransaction', <String, dynamic>{
          'sku': sku,
        });
        result = json.encode(result);

        Map<String, dynamic> param = json.decode(result.toString());
        PurchasedItem item = PurchasedItem.fromJSON(param);
        return item;
      } catch (err) {
        //Error is triggered by the user pressing cancel
        print('Caused err. Set additionalSuccessPurchaseListenerIOS.');
        print(err);
        await _addAdditionalSuccessPurchaseListenerIOS();
        _purchaseSub = onAdditionalSuccessPurchaseIOS.listen((data) {
          _removePurchaseListener();
          Map<String, dynamic> param = json.decode(data.toString());
          PurchasedItem item = PurchasedItem.fromJSON(param);
          return item; //this return is within in an async callback
        });
        //Missing return, so we break out of the if/else and throw the PlatformException below
      }
    }
    throw PlatformException(
        code: _platform.operatingSystem, message: "platform not supported");
```

**Comment by mrmikezhang** [comment]
@alexandergottlieb nice one Alex, thanks for that. Yes, that's definitely the problem.

**Comment by hyochan** [comment]
`2.0.0+` has raised today. Please feel free to reopen after trying out `2.0.0+5` or above.
