### ISSUE TITLE
Error when calling FlutterInappPurchase#prepare

### ISSUE THREAD

**Issue by GervaisYO** [dooboolab/flutter_inapp_purchase#7]
Hi,

i'm using version 0.4.3 in an android simulator and i'm getting following error when calling FlutterInappPurchase#prepare:
Flutter Platform Exception(prepare, response Code: 3, ).

Any idea what i'm doing wrong here?
Thank you.

**Comment by dooboolab** [comment]
@GervaisYO `IAP` feature will not work in android emulator. You should try it on the real device.
