### ISSUE TITLE
[Feature Request] Android subscription, missing developer payload field

### ISSUE THREAD

**Issue by rostopira** [dooboolab/flutter_inapp_purchase#70]
When using back-end based subscription verification/renewal, `AccountId` is required
See `BillingFlowParams.Builder.setAccountId` method

**Comment by rostopira** [comment]
Find out, that `setAccoundId` isn't the same as developer payload https://github.com/googlesamples/android-play-billing/issues/78

**Comment by hyochan** [comment]
Could you be bit more specific what should be implemented? What should we do to this plugin?

**Comment by rostopira** [comment]
I've already done this for myself
I can provide a PR, but it changes dependency from official android billing to this fork https://github.com/DimaDake/billing

Developer payload field allows attach string (user or group id) to purchase (without this realtime developer notifications is useless)

**Comment by hyochan** [comment]
@rostopira It would be fine to make some `dep` to your work as long as both are maintained. Also, do you mind upgrading your work to `implementation 'com.android.billingclient:billing:1.2.2`? I see this is recent currently.

**Comment by rostopira** [comment]
@hyochan Maybe I should put that fork source directly in this repo and we will maintain it here? Or just update to `1.2.2` and forget about it?

**Comment by hyochan** [comment]
@rostopira Merging would be good decision too to reduce some `fragmentations`. I think it could be better.

**Comment by samarthagarwal** [comment]
@rostopira can you guide me of how to implement developer payload?

**Comment by marcglasberg** [comment]
We also need this.

**Comment by hyochan** [comment]
`2.0.0+` has raised today. Please feel free to reopen after trying out `2.0.0+5` or above.
You can pass `developerId` when you attempt `purchase` or `subscription`.
