### ISSUE TITLE
xCode build fails with second target, complains of missing FlutterInappPurchasePlugin.h

### ISSUE THREAD

**Issue by NickM-27** [dooboolab/flutter_inapp_purchase#76]
### Version of flutter_inapp_purchase

0.9.2

### Platforms you faced the error (IOS or Android or both?)

iOS, haven't tested Android but this happens in xCode

### Expected behavior

Build correctly

### Actual behavior

Fails build

### Tested environment (Emulator? Real Device?)

Both simulator and real device

### Steps to reproduce the behavior

Add in_app plugin, add second target to xCode (I added a today extension)

**Comment by hyochan** [comment]
This issue doesn't seem to be clear enough to help you out. Could you try out the `example` project see  if it works correctly and try to see the differences with your project?
