### ISSUE TITLE
consumeAllItems: no-ops in ios

### ISSUE THREAD

**Issue by dark-chocolate** [dooboolab/flutter_inapp_purchase#78]
### Version of flutter_inapp_purchase
0.9.2

### Platforms you faced the error (IOS or Android or both?)
iOS

### Expected behavior
It should show the product/items to make a purchase. 

### Actual behavior
`print('consumeAllItems: $msg');` // returns consumeAllItems: no-ops in ios

### Tested environment (Emulator? Real Device?)
Both

### Steps to reproduce the behavior
Using sample code, I changed `_productLists` to include my item's from the app store that I created.

**Comment by hyochan** [comment]
@dark-chocolate This is expected. `consumeAllItems` only affects `Android`.
