### ISSUE TITLE
After buying product, it throws PlatformException(InappPurchasePlugin, purchase error, responseCode:0)

### ISSUE THREAD

**Issue by figengungor** [dooboolab/flutter_inapp_purchase#79]
### Version of flutter_inapp_purchase
flutter_inapp_purchase: ^0.9.2

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
After buying product I expect to get PurchasedItem.

### Actual behavior
After buying product I get the following exception: PlatformException(InappPurchasePlugin, purchase error, responseCode:0) which is logged here https://github.com/dooboolab/flutter_inapp_purchase/blob/ca88fda50229f090602ab3a6b186fff80536079d/android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java#L430 indicates that products are null.

### Tested environment (Emulator? Real Device?)
Real Device

flutter doctor -v

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-TR)
    • Flutter version 1.2.1 at /Users/figengungor/Documents/development/flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/figengungor/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • LG H850 • LGH85074f531b6 • android-arm64 • Android 8.0.0 (API 26)
```

### Steps to reproduce the behavior

Calling this function and after completing payment steps in test account and getting payment success, I got the mentioned PlatformException above.

```
 Future<PurchasedItem> buyProduct(IAPItem data) async {
    await _initConnection();
    PurchasedItem purchasedItem =  await FlutterInappPurchase.buyProduct(data.productId);
    if(purchasedItem!=null) _isSubscribedController.add(true);
    await _endConnection();
    return purchasedItem;
  }

Future<String> _initConnection() async {
    return FlutterInappPurchase.initConnection;
  }

  Future<String> _endConnection() async {
    return FlutterInappPurchase.endConnection;
  }

```

**Comment by letiagoalves** [comment]
I am having the same problem on a real device (Nexus 5 / Android 8)

**Comment by figengungor** [comment]
The workaround for me was fetching purchases again after I get PlatformException after buying subscription.

**Comment by hyochan** [comment]
I hope you guys to try out `example` project so we can talk on the same code.

**Comment by mliitfall** [comment]
Same issue with me! Any solution?

**Comment by SachinGanesh** [comment]
Try consuming the purchased item immediately after buying the product. I was facing the same issue. Fixed it by following below method
```dart
PurchasedItem purchased =
          await FlutterInappPurchase.buyProduct(item.productId);
   if (purchased != null) {
        print('>> Purchased - ${purchased.toString()}');
        FlutterInappPurchase.consumePurchase(purchased.purchaseToken); //Consume Item Fixes PlatformException issue
   } else {
        print(">> Purchase Failed");
}

**Comment by letiagoalves** [comment]
@SachinGanesh `FlutterInappPurchase.buyProduct` throws with `PlatformException` and therefore the following code won't run. So I guess we are facing different problems.

**Comment by Lastmanstanding** [comment]
We have the same issue, same exception, same 0.9.2 version, also real device. 

The issue only applies to our subscriptions products, though. Our consumable products works like a charm. 
As mentioned earlier, a workaround is catching the exception and read through the purchased products from `getAvailablePurchases`. Eg. like:
```dart
PurchasedItem purchasedItem;
List<PurchasedItem> allOfThem;
try {
   purchasedItem = await FlutterInappPurchase.buyProduct(productId);
} catch (err) {
   allOfThem = await FlutterInappPurchase.getAvailablePurchases();
   // find your purchasedItem from the List
}
```

**Comment by ollydixon** [comment]
Also testing on a real device. Turns out if it's a sandbox user it screws up the product and we cannot purchase it again (This In-App Purchase Has Aready Been Bought). Looks like someone forgot to add ```Platform.isIOS``` somewhere.

Error message is ```Unsupported operation: consume purchase is not available on Android```

**Comment by hyochan** [comment]
Looks like this is fixed in `2.0.0+4` or above.

**Comment by phuc-koli** [comment]
@ollydixon 
Did you find the solution for "This In-App Purchase Has Already Been Bought" error?

**Comment by Lastmanstanding** [comment]
The flutter team has developed an [in-app package](https://pub.dev/packages/in_app_purchase), now. Would go with that, instead.

**Comment by phuc-koli** [comment]
I actually tried that package and got same issue, then I switched to this package @Lastmanstanding

**Comment by ollydixon** [comment]
@Lastmanstanding @phuc-koli the reason I came to this package was cause the Flutter official one was far worse. ;-P
