### ISSUE TITLE
Modifying Subscriptions

### ISSUE THREAD

**Issue by mwesolek** [dooboolab/flutter_inapp_purchase#8]
When modifying subscriptions on iOS in Sandbox environment the purchase fails even though it is updated on the iTunes Store. With version 0.4.3 I was able to modify the subscription once and then it would fail but for some reason right now it is failing every time after initial purchase on 0.5.0.

**On Version 0.4.3**
The error is: **type 'String' is not a subtype of type 'Map<String, dynamic>'**

The line seems to be on 274: `Map<String, dynamic> param = json.decode(result.toString());`

**On Version 0.5.0**
The error is with invoking: `await _channel
          .invokeMethod('buyProductWithFinishTransaction', <String, dynamic>{
        'sku': sku,
      });`

It seems to fail on the native layer.

**Comment by mwesolek** [comment]
@dooboolab I wrapped with the try catch, and here is the error message:

**flutter: PlatformException(ERROR, Purcahse failed!, null)**

**Comment by dooboolab** [comment]
@mwesolek Your purchased has failed for some reason. The bridge is working fine.
```
case SKPaymentTransactionStateFailed:
                if (result == nil) return;
                [requestedPayments removeObjectForKey:transaction.payment];
                result([FlutterError errorWithCode:@"ERROR" message:@"Purcahse failed!" details:nil]);
                break;
```

**Comment by mwesolek** [comment]
@dooboolab I have checked out the version 0.5.1 error messages, and now it is crashing the entire app when the modify subscription prompt pops up. 

The error message given before the crash is: **Unsupported value: Error Domain=SKErrorDomain Code=2 "Cannot connect to iTunes Store" UserInfo={NSLocalizedDescription=Cannot connect to iTunes Store} of type NSError**

I know this is not a connection issue because I have been able to make the initial purchase and connect to everything else in the app.

**Comment by dooboolab** [comment]
@mwesolek Ok. Sorry that I couldn't test firmly before publishing because I wasn't able to reproduce the problem with the `buySubscription`. I've just released to `0.5.2` needing to fix the crashing. Could you please test again?

**Comment by mwesolek** [comment]
@dooboolab no worries! After testing again, I got the error:

**flutter: PlatformException(E_UNKNOWN, An unknown or unexpected error has occured. Please try again later., null)**

I'm not sure if this is an error on Apple's end with the sandboxing, or if this is something that is an error with the package. It seems to be registering the update but the plugin is saying it failed.

**Comment by dooboolab** [comment]
@mwesolek This is message from ios side and not from the bridging. So I think you should check if your IAP product is valid.

**Comment by mwesolek** [comment]
@dooboolab The product is valid and I am able to subscribe to it, but the package is throwing the unknown error even though it is subscribed. It could be an issue with the sandboxing on Apple's end.

**Comment by dooboolab** [comment]
@mwesolek Ok. Please come back again when you have any news for this one. I currently have no idea why this is occurring. I will leave this as an issue and see who's coming next.

**Comment by hyochan** [comment]
Thanks for the reminder. I hope someone to get evolved in this problem since this wasn't in my test case. I want some reproducible circumstances so I can debug. Hope for contributions too.

**Comment by kmckinley** [comment]
@hyochan 100% understand.  I need to get our IAP update out so in the meantime, I'm not going to expose the ability to change a subscription.  I'm slammed right now, but when I get some free time I'll try to jump in to contribute.

**Comment by hyochan** [comment]
`2.0.0+` has raised today. Please feel free to reopen after trying out `2.0.0+5` or above.
