### ISSUE TITLE
Improve error handling[Suggestion]

### ISSUE THREAD

**Issue by figengungor** [dooboolab/flutter_inapp_purchase#81]
### Version of flutter_inapp_purchase
flutter_inapp_purchase: ^0.9.2

Can we create some error codes to handle errors properly? Currently code in PlatformException is assigned from call.method. For example there are these [response codes](https://developer.android.com/reference/com/android/billingclient/api/BillingClient.BillingResponse.html) for Billing Api for Android. I don't know about iOS part but can we create some error codes which is proper to error condition so we can show related information to user when the error occurs?

**Comment by hyochan** [comment]
@figengungor Hi. Thank you for the issue. There are already [error codes](https://github.com/dooboolab/flutter_inapp_purchase/blob/ca88fda50229f090602ab3a6b186fff80536079d/android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java#L106-L111) sending to `JS` in android.
