### ISSUE TITLE
Calling getPurchaseHistory to check if a user bought a product requires the iTunes password on iOS

### ISSUE THREAD

**Issue by MasiaVittorio** [dooboolab/flutter_inapp_purchase#84]
### Version of flutter_inapp_purchase
^0.8.8+2

### Platforms you faced the error (IOS or Android or both?)
Only iOS, in fact on Android it calls it flawlessly without any user interaction

### Expected behavior
As on Android, it should return the history without user access. Is it because of how Apple handles this infos? Or maybe because my app is not fully released on AppStore yet?

### Actual behavior
When calling getPurchasesHistory on iOS, the iPhone launches a prompt that asks for the user ID and iTunes password.

### Tested environment (Emulator? Real Device?)
Real device: iPhone X (and various iPhone emulators also)

### Steps to reproduce the behavior
Just calling getPurchaseHistory on iOS

**Comment by hyochan** [comment]
I think this is expected in `iOS`. Please feel free to reopen if you find any news.
