### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method prepare on channel flutter_inapp)

### ISSUE THREAD

**Issue by bigearsenal** [dooboolab/flutter_inapp_purchase#86]
### Version of flutter_inapp_purchase
0.9.2
### Platforms you faced the error (IOS or Android or both?)
Android
### Expected behavior
initiated connection
### Actual behavior
Unhandled Exception: MissingPluginException(No implementation found for method prepare on channel flutter_inapp)
### Tested environment (Emulator? Real Device?)
Emulator
### Steps to reproduce the behavior
initialise app using FlutterInappPurchase.initConnection

**Comment by hyochan** [comment]
You should not be using this in emulator
