### ISSUE TITLE
AndroidInappPurchasePlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by magnuswikhog** [dooboolab/flutter_inapp_purchase#89]
When compiling a release build for Android, I get a Gradle warning that the plugin _"uses or overrides a deprecated API"_.

### Version of flutter_inapp_purchase
0.9.2

### Platforms you faced the error (IOS or Android or both?)
Android

### Expected behavior
No warnings from Gradle

### Actual behavior
    /development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inapp_purchase-0.9.2/android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java:354: warning: [deprecation] addOldSku(String) in Builder has been deprecated
        builder.addOldSku(oldSku);

### Tested environment (Emulator? Real Device?)
Emulator

### Steps to reproduce the behavior
Create a flutter app, add the plugin and run `android build apk --release` (with `Xlint:deprecated` to get the details)

**Comment by hyochan** [comment]
Thanks for reporting this. @magnuswikhog could you kindly add the newer API for the maintenance of the current repository?

**Comment by hyochan** [comment]
Fixed from `2.0.0+4`.

**Comment by egorges** [comment]
I got this message with **2.2.0**

> Note:   flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inapp_purchase-2.2.0/android/src/main/java/com/dooboolab/flutterinapppurchase/AndroidInappPurchasePlugin.java uses or overrides a deprecated API.

**Comment by ricardocaste** [comment]
The same issue with 2.2.0 and only in Android

**Comment by egorges** [comment]
Hello @hyochan , looks like it still happens in **2.2.0**.

**Comment by dikdableu** [comment]
I have the same issue with 2.2.0

**Comment by Zeynal7** [comment]
It is caused by deprecated API - `setOldSku(oldSku)`. I believe, it should be `setOldSku(oldSku, purchaseToken)`.

But, I am not quite sure how I should get the token. Is it with
`   final String token = call.argument("token"); ?`
