### ISSUE TITLE
Ability to get receipts for existing purchases

### ISSUE THREAD

**Issue by opensourcegps** [dooboolab/flutter_inapp_purchase#9]
Thanks for this great plugin!

Is it possible to get receipts data after fetching getAvailablePurchases? 

In case user re-installs the app, and purchases must be restored, currently there is no way to validate restored purchases and server side code must enable purchases without validation. This opens up back-end security holes, with properly crafted API calls. 

It would be great to have something like getReceipt(purchased_product_id).

**Comment by dooboolab** [comment]
@opensourcegps With my knowledge, you need to manage the receipt yourself on the server side after purchase.

**Comment by opensourcegps** [comment]
@dooboolab Yes, but once user completely reinstalled the app, they are new users for the server. There is no link to their previous installation and all receipts are left there. However purchases must be restored anyway.

**Comment by dooboolab** [comment]
@opensourcegps You can restore the purchase using `getAvailablePurchases`. You may also refer to [react-native-iap](https://github.com/dooboolab/react-native-iap) where this project exactly came from.

**Comment by dooboolab** [comment]
@opensourcegps You have to manage the `receipt` and save somewhere like in your database. You can get the `receipt` when you purchase the product. Get that `base64` code and try to reuse it in your scenario. Would that help you case?

**Comment by opensourcegps** [comment]
@dooboolab I guess it's hard to explain. Imagine the following scenario:

1. Install the app, purchase the product, save receipt to database.
2. Uninstall the app.
3. Install the same app again. Now, getAvailablePurchases will return the purchase, however you can not get old receipt from the database, because user re-installed the app and there is no connection in the new installation to the old one. No way to restore purchase with validation in this case.

In any case, this is not very critical, just will overall improve security of the app. Thanks for making this plugin, tried all of them and yours looks like clear winner.

**Comment by lukepighetti** [comment]
@opensourcegps Can you restore purchases, save receipt to your server, and use server to check if it's valid and be done with it?

**Comment by opensourcegps** [comment]
@lukepighetti there is no receipt available when restoring purchases in this plugin. Receipt is only available during initial purchase. That is the core of this issue.

**Comment by lukepighetti** [comment]
@opensourcegps Gotcha. How can I reproduce this?

**Comment by opensourcegps** [comment]
@lukepighetti sure, you can reproduce it like shown above:

1. Install the app, purchase the product, save receipt to database.
2. Uninstall the app.
3. Install the same app again. Try to restore purchases with validation.

**Comment by dark-chocolate** [comment]
@opensourcegps I don't understand why you have issues in this. Let me put the things in simple steps. 

1. Install the app, purchase the product, save receipt to database.
2. Uninstall the app. 
3. Install the app again, and use this logic

```
Future<Null> _getPurchaseHistory() async {
  List<PurchasedItem> items = await FlutterInappPurchase.getPurchaseHistory();

  // Fetch all the list where you are saving the tokens in your database.
  List<String> tokens = await fetchListHere()
  bool isVerified = false;
  for (PurchasedItem item in items) {
    if (tokens.contains(item.purchaseToken)) {
      isVerified = true;
      break;
    }
  }
  print("Verified = ${isVerified}");
}
```

**Comment by opensourcegps** [comment]
@dark-chocolate thanks for update, I think this issue is long closed and I worked around it. 

Just FYI, this issue is still present in your code too. getPurchaseHistory() returns IAPItem, and it does not have purchaseToken. So item.purchaseToken does not exists in your code. That's basically why this issue was opened in the first place.

Adding purchaseToken into IAPItem would solve this.

**Comment by dark-chocolate** [comment]
@opensourcegps I tested second part of it (`item.purchaseToken`), it does have valid tokens however one thing it doesn't possess is Order ID which starts with `GPA.123...` which is why I suggested you to use tokens instead of ID.

**Comment by opensourcegps** [comment]
@dark-chocolate if IAPItem has purchaseToken, then I can suggest updating docs. At the moment, according to docs, getPurchaseHistory returns List<IAPItem>, and List<IAPItem> does not have "purchaseToken".

**Comment by dark-chocolate** [comment]
@opensourcegps I tried this plugin yesterday, so I am not sure if this was missing before (not the docs but actually the real tokens). The latest version `0.9.2` has it.
