### ISSUE TITLE
finishTransaction expection

### ISSUE THREAD

**Issue by qmwdy** [dooboolab/flutter_inapp_purchase#99]
### Version of flutter_inapp_purchase
2.0.0+6
### Platforms you faced the error (IOS or Android or both?)
iOS
### Actual behavior
in flutter_inapp_purchase.dart, line 426, may cause expection.
use
      Map purchaseResultMap = json.decode(result.toString());
      PurchaseResult decoded = new PurchaseResult.fromJSON(purchaseResultMap);
to resolve
### Steps to reproduce the behavior

**Comment by hyochan** [comment]
Thanks for the bug report. Resolved in `2.0.0+7`.
